CREATE TABLE IF NOT EXISTS "__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL,
    CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId")
);

START TRANSACTION;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251021031408_InitialCreate') THEN
    CREATE TABLE empresas (
        id bigint GENERATED BY DEFAULT AS IDENTITY,
        razao_social character varying(250) NOT NULL,
        cnpj character varying(18),
        telefone character varying(20),
        celular character varying(20),
        email character varying(150),
        cep character varying(10),
        estado integer NOT NULL,
        cidade character varying(100),
        endereco character varying(500),
        numero character varying(20),
        bairro character varying(100),
        complemento character varying(150),
        observacoes character varying(2000),
        id_empresa bigint NOT NULL,
        ativo boolean NOT NULL,
        data_cadastro timestamp without time zone NOT NULL,
        data_alteracao timestamp without time zone NOT NULL,
        criado_por_usuario_id bigint,
        alterado_por_usuario_id bigint,
        empresa_id bigint,
        CONSTRAINT pk_empresas PRIMARY KEY (id),
        CONSTRAINT "FK_empresas_empresas_empresa_id" FOREIGN KEY (empresa_id) REFERENCES empresas (id)
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251021031408_InitialCreate') THEN
    CREATE TABLE clientes (
        id bigint GENERATED BY DEFAULT AS IDENTITY,
        cep character varying(10),
        estado integer NOT NULL,
        cidade character varying(100),
        endereco character varying(500),
        numero character varying(20),
        bairro character varying(100),
        complemento character varying(150),
        observacoes character varying(2000),
        foto_cliente character varying(10000),
        documento_rg character varying(10000),
        id_empresa bigint NOT NULL,
        ativo boolean NOT NULL,
        data_cadastro timestamp without time zone NOT NULL,
        data_alteracao timestamp without time zone NOT NULL,
        criado_por_usuario_id bigint,
        alterado_por_usuario_id bigint,
        empresa_id bigint,
        tipo_pessoa integer NOT NULL,
        nome character varying(250) NOT NULL,
        data_nascimento timestamp without time zone,
        cpf character varying(14),
        rg character varying(20),
        cnpj character varying(18),
        email character varying(150),
        telefone character varying(20),
        celular character varying(20),
        CONSTRAINT pk_clientes PRIMARY KEY (id),
        CONSTRAINT "FK_clientes_empresas_empresa_id" FOREIGN KEY (empresa_id) REFERENCES empresas (id)
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251021031408_InitialCreate') THEN
    CREATE TABLE leads (
        id bigint GENERATED BY DEFAULT AS IDENTITY,
        nome character varying(250) NOT NULL,
        celular character varying(20) NOT NULL,
        email character varying(150),
        tipo_retorno_contato integer NOT NULL DEFAULT 1,
        status integer NOT NULL DEFAULT 1,
        contexto text,
        ativo boolean NOT NULL DEFAULT TRUE,
        id_empresa bigint NOT NULL,
        data_cadastro timestamp without time zone NOT NULL,
        data_alteracao timestamp without time zone NOT NULL,
        criado_por_usuario_id bigint,
        alterado_por_usuario_id bigint,
        empresa_id bigint,
        CONSTRAINT pk_leads PRIMARY KEY (id),
        CONSTRAINT "FK_leads_empresas_empresa_id" FOREIGN KEY (empresa_id) REFERENCES empresas (id)
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251021031408_InitialCreate') THEN
    CREATE TABLE report_templates (
        id bigint GENERATED BY DEFAULT AS IDENTITY,
        nome character varying(200) NOT NULL,
        tipo_entidade character varying(100) NOT NULL,
        descricao character varying(500),
        template_json text NOT NULL,
        is_padrao boolean NOT NULL DEFAULT FALSE,
        ativo boolean NOT NULL DEFAULT TRUE,
        id_empresa bigint NOT NULL,
        data_cadastro timestamp without time zone NOT NULL,
        data_alteracao timestamp without time zone NOT NULL,
        criado_por_usuario_id bigint,
        alterado_por_usuario_id bigint,
        empresa_id bigint,
        CONSTRAINT pk_report_templates PRIMARY KEY (id),
        CONSTRAINT "FK_report_templates_empresas_empresa_id" FOREIGN KEY (empresa_id) REFERENCES empresas (id)
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251021031408_InitialCreate') THEN
    CREATE TABLE usuarios (
        id bigint GENERATED BY DEFAULT AS IDENTITY,
        nome character varying(250) NOT NULL,
        email character varying(150) NOT NULL,
        cpf character varying(14),
        telefone character varying(20),
        perfil integer NOT NULL,
        ultimo_login timestamp without time zone,
        senha_hash character varying(255) NOT NULL,
        confirmar_senha text,
        observacoes character varying(2000),
        id_empresa bigint NOT NULL,
        ativo boolean NOT NULL DEFAULT TRUE,
        data_cadastro timestamp without time zone NOT NULL,
        data_alteracao timestamp without time zone NOT NULL,
        criado_por_usuario_id bigint,
        alterado_por_usuario_id bigint,
        CONSTRAINT pk_usuarios PRIMARY KEY (id),
        CONSTRAINT "FK_usuarios_empresas_id_empresa" FOREIGN KEY (id_empresa) REFERENCES empresas (id) ON DELETE SET NULL
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251021031408_InitialCreate') THEN
    CREATE TABLE veiculo_cores (
        id bigint GENERATED BY DEFAULT AS IDENTITY,
        descricao character varying(50) NOT NULL,
        id_empresa bigint NOT NULL,
        ativo boolean NOT NULL,
        data_cadastro timestamp without time zone NOT NULL,
        data_alteracao timestamp without time zone NOT NULL,
        criado_por_usuario_id bigint,
        alterado_por_usuario_id bigint,
        empresa_id bigint,
        CONSTRAINT pk_veiculo_cores PRIMARY KEY (id),
        CONSTRAINT "FK_veiculo_cores_empresas_empresa_id" FOREIGN KEY (empresa_id) REFERENCES empresas (id)
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251021031408_InitialCreate') THEN
    CREATE TABLE veiculo_filiais (
        id bigint GENERATED BY DEFAULT AS IDENTITY,
        descricao character varying(100) NOT NULL,
        id_empresa bigint NOT NULL,
        ativo boolean NOT NULL,
        data_cadastro timestamp without time zone NOT NULL,
        data_alteracao timestamp without time zone NOT NULL,
        criado_por_usuario_id bigint,
        alterado_por_usuario_id bigint,
        empresa_id bigint,
        CONSTRAINT pk_veiculo_filiais PRIMARY KEY (id),
        CONSTRAINT "FK_veiculo_filiais_empresas_empresa_id" FOREIGN KEY (empresa_id) REFERENCES empresas (id)
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251021031408_InitialCreate') THEN
    CREATE TABLE veiculo_localizacoes (
        id bigint GENERATED BY DEFAULT AS IDENTITY,
        descricao character varying(100) NOT NULL,
        id_empresa bigint NOT NULL,
        ativo boolean NOT NULL,
        data_cadastro timestamp without time zone NOT NULL,
        data_alteracao timestamp without time zone NOT NULL,
        criado_por_usuario_id bigint,
        alterado_por_usuario_id bigint,
        empresa_id bigint,
        CONSTRAINT pk_veiculo_localizacoes PRIMARY KEY (id),
        CONSTRAINT "FK_veiculo_localizacoes_empresas_empresa_id" FOREIGN KEY (empresa_id) REFERENCES empresas (id)
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251021031408_InitialCreate') THEN
    CREATE TABLE veiculo_marcas (
        id bigint GENERATED BY DEFAULT AS IDENTITY,
        descricao character varying(100) NOT NULL,
        id_empresa bigint NOT NULL,
        ativo boolean NOT NULL,
        data_cadastro timestamp without time zone NOT NULL,
        data_alteracao timestamp without time zone NOT NULL,
        criado_por_usuario_id bigint,
        alterado_por_usuario_id bigint,
        empresa_id bigint,
        CONSTRAINT pk_veiculo_marcas PRIMARY KEY (id),
        CONSTRAINT "FK_veiculo_marcas_empresas_empresa_id" FOREIGN KEY (empresa_id) REFERENCES empresas (id)
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251021031408_InitialCreate') THEN
    CREATE TABLE audit_logs (
        id bigint GENERATED BY DEFAULT AS IDENTITY,
        usuario_id bigint,
        usuario_nome character varying(250),
        usuario_email character varying(150),
        entidade_nome character varying(100) NOT NULL,
        entidade_display_name character varying(100),
        entidade_id character varying(50) NOT NULL,
        tipo_operacao integer NOT NULL,
        tabela_nome character varying(100),
        valores_antigos text,
        valores_novos text,
        campos_alterados text,
        ip_cliente character varying(45),
        user_agent character varying(500),
        url_requisicao character varying(500),
        metodo_http character varying(10),
        sucesso boolean NOT NULL,
        mensagem_erro character varying(2000),
        duracao_ms bigint,
        data_hora timestamp without time zone NOT NULL,
        id_empresa bigint NOT NULL,
        ativo boolean NOT NULL,
        data_cadastro timestamp without time zone NOT NULL,
        data_alteracao timestamp without time zone NOT NULL,
        criado_por_usuario_id bigint,
        alterado_por_usuario_id bigint,
        CONSTRAINT pk_audit_logs PRIMARY KEY (id),
        CONSTRAINT "FK_audit_logs_empresas_id_empresa" FOREIGN KEY (id_empresa) REFERENCES empresas (id) ON DELETE SET NULL,
        CONSTRAINT "FK_audit_logs_usuarios_usuario_id" FOREIGN KEY (usuario_id) REFERENCES usuarios (id) ON DELETE SET NULL
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251021031408_InitialCreate') THEN
    CREATE TABLE veiculo_marca_modelos (
        id bigint GENERATED BY DEFAULT AS IDENTITY,
        descricao character varying(100) NOT NULL,
        id_veiculo_marca bigint,
        "VeiculoMarcaId" bigint,
        id_empresa bigint NOT NULL,
        ativo boolean NOT NULL,
        data_cadastro timestamp without time zone NOT NULL,
        data_alteracao timestamp without time zone NOT NULL,
        criado_por_usuario_id bigint,
        alterado_por_usuario_id bigint,
        CONSTRAINT pk_veiculo_marca_modelos PRIMARY KEY (id),
        CONSTRAINT "FK_veiculo_marca_modelos_empresas_id_empresa" FOREIGN KEY (id_empresa) REFERENCES empresas (id) ON DELETE SET NULL,
        CONSTRAINT "FK_veiculo_marca_modelos_veiculo_marcas_VeiculoMarcaId" FOREIGN KEY ("VeiculoMarcaId") REFERENCES veiculo_marcas (id),
        CONSTRAINT "FK_veiculo_marca_modelos_veiculo_marcas_id_veiculo_marca" FOREIGN KEY (id_veiculo_marca) REFERENCES veiculo_marcas (id) ON DELETE SET NULL
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251021031408_InitialCreate') THEN
    CREATE TABLE veiculos (
        id bigint GENERATED BY DEFAULT AS IDENTITY,
        codigo character varying(50) NOT NULL,
        placa character varying(10) NOT NULL,
        situacao integer NOT NULL,
        chassi character varying(17),
        renavam character varying(11),
        id_veiculo_marca bigint NOT NULL,
        id_veiculo_marca_modelo bigint NOT NULL,
        ano_fabricacao integer NOT NULL,
        ano_modelo integer NOT NULL,
        id_veiculo_cor bigint,
        motorizacao text,
        capacidade_porta_malas integer,
        combustivel integer NOT NULL,
        cambio integer NOT NULL,
        tipo_veiculo integer NOT NULL,
        especie integer NOT NULL,
        numero_portas integer NOT NULL,
        pericia_cautelar integer NOT NULL,
        origem_veiculo integer NOT NULL,
        preco_compra numeric(18,2),
        id_cliente bigint NOT NULL,
        data_entrada timestamp without time zone NOT NULL,
        km_entrada numeric(18,2),
        data_saida timestamp without time zone,
        km_saida numeric(18,2),
        preco_venda numeric(18,2),
        status integer NOT NULL,
        id_veiculo_filial bigint,
        id_veiculo_localizacao bigint,
        observacoes character varying(2000),
        opcionais text,
        id_empresa bigint NOT NULL,
        ativo boolean NOT NULL,
        data_cadastro timestamp without time zone NOT NULL,
        data_alteracao timestamp without time zone NOT NULL,
        criado_por_usuario_id bigint,
        alterado_por_usuario_id bigint,
        CONSTRAINT pk_veiculos PRIMARY KEY (id),
        CONSTRAINT "FK_veiculos_clientes_id_cliente" FOREIGN KEY (id_cliente) REFERENCES clientes (id) ON DELETE SET NULL,
        CONSTRAINT "FK_veiculos_empresas_id_empresa" FOREIGN KEY (id_empresa) REFERENCES empresas (id) ON DELETE SET NULL,
        CONSTRAINT "FK_veiculos_veiculo_cores_id_veiculo_cor" FOREIGN KEY (id_veiculo_cor) REFERENCES veiculo_cores (id) ON DELETE SET NULL,
        CONSTRAINT "FK_veiculos_veiculo_filiais_id_veiculo_filial" FOREIGN KEY (id_veiculo_filial) REFERENCES veiculo_filiais (id) ON DELETE SET NULL,
        CONSTRAINT "FK_veiculos_veiculo_localizacoes_id_veiculo_localizacao" FOREIGN KEY (id_veiculo_localizacao) REFERENCES veiculo_localizacoes (id) ON DELETE SET NULL,
        CONSTRAINT "FK_veiculos_veiculo_marca_modelos_id_veiculo_marca_modelo" FOREIGN KEY (id_veiculo_marca_modelo) REFERENCES veiculo_marca_modelos (id) ON DELETE SET NULL,
        CONSTRAINT "FK_veiculos_veiculo_marcas_id_veiculo_marca" FOREIGN KEY (id_veiculo_marca) REFERENCES veiculo_marcas (id) ON DELETE SET NULL
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251021031408_InitialCreate') THEN
    CREATE TABLE veiculo_documentos (
        id bigint GENERATED BY DEFAULT AS IDENTITY,
        tipo_documento integer NOT NULL,
        documento character varying(500) NOT NULL,
        observacoes character varying(500) NOT NULL,
        data_upload timestamp without time zone NOT NULL,
        id_veiculo bigint NOT NULL,
        id_empresa bigint NOT NULL,
        ativo boolean NOT NULL,
        data_cadastro timestamp without time zone NOT NULL,
        data_alteracao timestamp without time zone NOT NULL,
        criado_por_usuario_id bigint,
        alterado_por_usuario_id bigint,
        CONSTRAINT pk_veiculo_documentos PRIMARY KEY (id),
        CONSTRAINT "FK_veiculo_documentos_empresas_id_empresa" FOREIGN KEY (id_empresa) REFERENCES empresas (id) ON DELETE SET NULL,
        CONSTRAINT "FK_veiculo_documentos_veiculos_id_veiculo" FOREIGN KEY (id_veiculo) REFERENCES veiculos (id) ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251021031408_InitialCreate') THEN
    CREATE TABLE veiculo_fotos (
        id bigint GENERATED BY DEFAULT AS IDENTITY,
        nome_arquivo character varying(255) NOT NULL,
        caminho_arquivo character varying(500) NOT NULL,
        foto character varying(10000) NOT NULL,
        descricao character varying(200),
        data_upload timestamp without time zone NOT NULL,
        principal boolean NOT NULL,
        id_veiculo bigint NOT NULL,
        id_empresa bigint NOT NULL,
        ativo boolean NOT NULL,
        data_cadastro timestamp without time zone NOT NULL,
        data_alteracao timestamp without time zone NOT NULL,
        criado_por_usuario_id bigint,
        alterado_por_usuario_id bigint,
        CONSTRAINT pk_veiculo_fotos PRIMARY KEY (id),
        CONSTRAINT "FK_veiculo_fotos_empresas_id_empresa" FOREIGN KEY (id_empresa) REFERENCES empresas (id) ON DELETE SET NULL,
        CONSTRAINT "FK_veiculo_fotos_veiculos_id_veiculo" FOREIGN KEY (id_veiculo) REFERENCES veiculos (id) ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251021031408_InitialCreate') THEN
    CREATE INDEX "IX_audit_logs_data_hora" ON audit_logs (data_hora);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251021031408_InitialCreate') THEN
    CREATE INDEX "IX_audit_logs_entidade_nome_entidade_id" ON audit_logs (entidade_nome, entidade_id);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251021031408_InitialCreate') THEN
    CREATE INDEX "IX_audit_logs_id_empresa" ON audit_logs (id_empresa);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251021031408_InitialCreate') THEN
    CREATE INDEX "IX_audit_logs_usuario_id" ON audit_logs (usuario_id);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251021031408_InitialCreate') THEN
    CREATE INDEX ix_cliente_nome ON clientes (nome);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251021031408_InitialCreate') THEN
    CREATE UNIQUE INDEX "IX_clientes_cnpj" ON clientes (cnpj) WHERE cnpj IS NOT NULL;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251021031408_InitialCreate') THEN
    CREATE UNIQUE INDEX "IX_clientes_cpf" ON clientes (cpf) WHERE cpf IS NOT NULL;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251021031408_InitialCreate') THEN
    CREATE INDEX "IX_clientes_empresa_id" ON clientes (empresa_id);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251021031408_InitialCreate') THEN
    CREATE INDEX "IX_empresas_empresa_id" ON empresas (empresa_id);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251021031408_InitialCreate') THEN
    CREATE INDEX "IX_leads_empresa_id" ON leads (empresa_id);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251021031408_InitialCreate') THEN
    CREATE INDEX "IX_report_templates_empresa_id" ON report_templates (empresa_id);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251021031408_InitialCreate') THEN
    CREATE INDEX "IX_report_templates_tipo_entidade" ON report_templates (tipo_entidade);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251021031408_InitialCreate') THEN
    CREATE INDEX "IX_report_templates_tipo_entidade_is_padrao" ON report_templates (tipo_entidade, is_padrao);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251021031408_InitialCreate') THEN
    CREATE INDEX "IX_usuarios_id_empresa" ON usuarios (id_empresa);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251021031408_InitialCreate') THEN
    CREATE UNIQUE INDEX "IX_veiculo_cores_descricao" ON veiculo_cores (descricao);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251021031408_InitialCreate') THEN
    CREATE INDEX "IX_veiculo_cores_empresa_id" ON veiculo_cores (empresa_id);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251021031408_InitialCreate') THEN
    CREATE INDEX "IX_veiculo_cores_id_empresa" ON veiculo_cores (id_empresa);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251021031408_InitialCreate') THEN
    CREATE INDEX "IX_veiculo_documentos_id_empresa" ON veiculo_documentos (id_empresa);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251021031408_InitialCreate') THEN
    CREATE INDEX "IX_veiculo_documentos_id_veiculo" ON veiculo_documentos (id_veiculo);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251021031408_InitialCreate') THEN
    CREATE UNIQUE INDEX "IX_veiculo_filiais_descricao" ON veiculo_filiais (descricao);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251021031408_InitialCreate') THEN
    CREATE INDEX "IX_veiculo_filiais_empresa_id" ON veiculo_filiais (empresa_id);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251021031408_InitialCreate') THEN
    CREATE INDEX "IX_veiculo_filiais_id_empresa" ON veiculo_filiais (id_empresa);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251021031408_InitialCreate') THEN
    CREATE INDEX "IX_veiculo_fotos_id_empresa" ON veiculo_fotos (id_empresa);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251021031408_InitialCreate') THEN
    CREATE INDEX "IX_veiculo_fotos_id_veiculo" ON veiculo_fotos (id_veiculo);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251021031408_InitialCreate') THEN
    CREATE UNIQUE INDEX "IX_veiculo_localizacoes_descricao" ON veiculo_localizacoes (descricao);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251021031408_InitialCreate') THEN
    CREATE INDEX "IX_veiculo_localizacoes_empresa_id" ON veiculo_localizacoes (empresa_id);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251021031408_InitialCreate') THEN
    CREATE INDEX "IX_veiculo_localizacoes_id_empresa" ON veiculo_localizacoes (id_empresa);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251021031408_InitialCreate') THEN
    CREATE INDEX "IX_veiculo_marca_modelos_id_empresa" ON veiculo_marca_modelos (id_empresa);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251021031408_InitialCreate') THEN
    CREATE INDEX "IX_veiculo_marca_modelos_id_veiculo_marca" ON veiculo_marca_modelos (id_veiculo_marca);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251021031408_InitialCreate') THEN
    CREATE INDEX "IX_veiculo_marca_modelos_VeiculoMarcaId" ON veiculo_marca_modelos ("VeiculoMarcaId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251021031408_InitialCreate') THEN
    CREATE UNIQUE INDEX "IX_veiculo_marcas_descricao" ON veiculo_marcas (descricao);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251021031408_InitialCreate') THEN
    CREATE INDEX "IX_veiculo_marcas_empresa_id" ON veiculo_marcas (empresa_id);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251021031408_InitialCreate') THEN
    CREATE INDEX "IX_veiculo_marcas_id_empresa" ON veiculo_marcas (id_empresa);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251021031408_InitialCreate') THEN
    CREATE UNIQUE INDEX "IX_veiculos_chassi" ON veiculos (chassi) WHERE chassi IS NOT NULL;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251021031408_InitialCreate') THEN
    CREATE UNIQUE INDEX "IX_veiculos_codigo" ON veiculos (codigo);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251021031408_InitialCreate') THEN
    CREATE INDEX "IX_veiculos_id_cliente" ON veiculos (id_cliente);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251021031408_InitialCreate') THEN
    CREATE INDEX "IX_veiculos_id_empresa" ON veiculos (id_empresa);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251021031408_InitialCreate') THEN
    CREATE INDEX "IX_veiculos_id_veiculo_cor" ON veiculos (id_veiculo_cor);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251021031408_InitialCreate') THEN
    CREATE INDEX "IX_veiculos_id_veiculo_filial" ON veiculos (id_veiculo_filial);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251021031408_InitialCreate') THEN
    CREATE INDEX "IX_veiculos_id_veiculo_localizacao" ON veiculos (id_veiculo_localizacao);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251021031408_InitialCreate') THEN
    CREATE INDEX "IX_veiculos_id_veiculo_marca" ON veiculos (id_veiculo_marca);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251021031408_InitialCreate') THEN
    CREATE INDEX "IX_veiculos_id_veiculo_marca_modelo" ON veiculos (id_veiculo_marca_modelo);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251021031408_InitialCreate') THEN
    CREATE UNIQUE INDEX "IX_veiculos_placa" ON veiculos (placa);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251021031408_InitialCreate') THEN
    CREATE UNIQUE INDEX "IX_veiculos_renavam" ON veiculos (renavam) WHERE renavam IS NOT NULL;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251021031408_InitialCreate') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20251021031408_InitialCreate', '9.0.9');
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251105054612_Seila') THEN
    ALTER TABLE audit_logs DROP COLUMN entidade_display_name;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251105054612_Seila') THEN
    ALTER TABLE audit_logs DROP COLUMN user_agent;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251105054612_Seila') THEN
    ALTER TABLE audit_logs DROP COLUMN usuario_email;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251105054612_Seila') THEN
    ALTER TABLE audit_logs DROP COLUMN usuario_nome;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251105054612_Seila') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20251105054612_Seila', '9.0.9');
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251105055950_RemoverColunasObsoletasAuditLog') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20251105055950_RemoverColunasObsoletasAuditLog', '9.0.9');
    END IF;
END $EF$;
COMMIT;

