// <auto-generated />
using System;
using FGT.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace FGT.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("FGT.Entidades.AliquotaImposto", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<decimal>("AliquotaPercentual")
                        .HasColumnType("decimal(5,2)")
                        .HasColumnName("aliquota_percentual");

                    b.Property<long?>("AlteradoPorUsuarioId")
                        .HasColumnType("bigint")
                        .HasColumnName("alterado_por_usuario_id");

                    b.Property<bool>("Ativo")
                        .HasColumnType("boolean")
                        .HasColumnName("ativo");

                    b.Property<string>("Cidade")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("cidade");

                    b.Property<long?>("CriadoPorUsuarioId")
                        .HasColumnType("bigint")
                        .HasColumnName("criado_por_usuario_id");

                    b.Property<DateTime>("DataAlteracao")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("data_alteracao");

                    b.Property<DateTime>("DataCadastro")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("data_cadastro");

                    b.Property<DateTime?>("DataVigenciaFinal")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("data_vigencia_final");

                    b.Property<DateTime>("DataVigenciaInicial")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("data_vigencia_inicial");

                    b.Property<long?>("EmpresaId")
                        .HasColumnType("bigint")
                        .HasColumnName("empresa_id");

                    b.Property<int?>("Estado")
                        .HasColumnType("integer")
                        .HasColumnName("estado");

                    b.Property<long>("IdEmpresa")
                        .HasColumnType("bigint")
                        .HasColumnName("id_empresa");

                    b.Property<string>("Observacoes")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("observacoes");

                    b.Property<int?>("RegimeTributario")
                        .HasColumnType("integer")
                        .HasColumnName("regime_tributario");

                    b.Property<int>("TipoImposto")
                        .HasColumnType("integer")
                        .HasColumnName("tipo_imposto");

                    b.HasKey("Id")
                        .HasName("pk_aliquotas_impostos");

                    b.HasIndex("EmpresaId");

                    b.ToTable("aliquotas_impostos");
                });

            modelBuilder.Entity("FGT.Entidades.Base.AuditLog", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("CamposAlterados")
                        .HasColumnType("text")
                        .HasColumnName("campos_alterados");

                    b.Property<DateTime>("DataHora")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("data_hora");

                    b.Property<long?>("DuracaoMs")
                        .HasColumnType("bigint")
                        .HasColumnName("duracao_ms");

                    b.Property<string>("EntidadeId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("entidade_id");

                    b.Property<string>("EntidadeNome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("entidade_nome");

                    b.Property<long>("IdEmpresa")
                        .HasColumnType("bigint")
                        .HasColumnName("id_empresa");

                    b.Property<string>("IpCliente")
                        .HasMaxLength(45)
                        .HasColumnType("character varying(45)")
                        .HasColumnName("ip_cliente");

                    b.Property<string>("MensagemErro")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("mensagem_erro");

                    b.Property<string>("MetodoHttp")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("metodo_http");

                    b.Property<bool>("Sucesso")
                        .HasColumnType("boolean")
                        .HasColumnName("sucesso");

                    b.Property<string>("TabelaNome")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("tabela_nome");

                    b.Property<int>("TipoOperacao")
                        .HasColumnType("integer")
                        .HasColumnName("tipo_operacao");

                    b.Property<string>("UrlRequisicao")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("url_requisicao");

                    b.Property<long?>("UsuarioId")
                        .HasColumnType("bigint")
                        .HasColumnName("usuario_id");

                    b.Property<string>("ValoresAntigos")
                        .HasColumnType("text")
                        .HasColumnName("valores_antigos");

                    b.Property<string>("ValoresNovos")
                        .HasColumnType("text")
                        .HasColumnName("valores_novos");

                    b.HasKey("Id")
                        .HasName("pk_audit_logs");

                    b.HasIndex("DataHora");

                    b.HasIndex("IdEmpresa");

                    b.HasIndex("UsuarioId");

                    b.HasIndex("EntidadeNome", "EntidadeId");

                    b.ToTable("audit_logs", (string)null);
                });

            modelBuilder.Entity("FGT.Entidades.Base.Cliente", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long?>("AlteradoPorUsuarioId")
                        .HasColumnType("bigint")
                        .HasColumnName("alterado_por_usuario_id");

                    b.Property<bool>("Ativo")
                        .HasColumnType("boolean")
                        .HasColumnName("ativo");

                    b.Property<string>("Bairro")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("bairro");

                    b.Property<string>("CEP")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("cep");

                    b.Property<string>("Celular")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("celular");

                    b.Property<string>("Cidade")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("cidade");

                    b.Property<string>("Cnpj")
                        .HasMaxLength(18)
                        .HasColumnType("character varying(18)")
                        .HasColumnName("cnpj");

                    b.Property<string>("Complemento")
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("complemento");

                    b.Property<string>("Cpf")
                        .HasMaxLength(14)
                        .HasColumnType("character varying(14)")
                        .HasColumnName("cpf");

                    b.Property<long?>("CriadoPorUsuarioId")
                        .HasColumnType("bigint")
                        .HasColumnName("criado_por_usuario_id");

                    b.Property<DateTime>("DataAlteracao")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("data_alteracao");

                    b.Property<DateTime>("DataCadastro")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("data_cadastro");

                    b.Property<DateTime?>("DataNascimento")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("data_nascimento");

                    b.Property<string>("DocumentoRG")
                        .HasMaxLength(10000)
                        .HasColumnType("character varying(10000)")
                        .HasColumnName("documento_rg");

                    b.Property<string>("Email")
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("email");

                    b.Property<long?>("EmpresaId")
                        .HasColumnType("bigint")
                        .HasColumnName("empresa_id");

                    b.Property<string>("Endereco")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("endereco");

                    b.Property<int>("Estado")
                        .HasColumnType("integer")
                        .HasColumnName("estado");

                    b.Property<string>("FotoCliente")
                        .HasMaxLength(10000)
                        .HasColumnType("character varying(10000)")
                        .HasColumnName("foto_cliente");

                    b.Property<long>("IdEmpresa")
                        .HasColumnType("bigint")
                        .HasColumnName("id_empresa");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)")
                        .HasColumnName("nome");

                    b.Property<string>("Numero")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("numero");

                    b.Property<string>("Observacoes")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("observacoes");

                    b.Property<string>("Rg")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("rg");

                    b.Property<string>("Telefone")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("telefone");

                    b.Property<int>("TipoPessoa")
                        .HasColumnType("integer")
                        .HasColumnName("tipo_pessoa");

                    b.HasKey("Id")
                        .HasName("pk_clientes");

                    b.HasIndex("Cnpj")
                        .IsUnique()
                        .HasFilter("cnpj IS NOT NULL");

                    b.HasIndex("Cpf")
                        .IsUnique()
                        .HasFilter("cpf IS NOT NULL");

                    b.HasIndex("EmpresaId");

                    b.HasIndex("Nome")
                        .HasDatabaseName("ix_cliente_nome");

                    b.ToTable("clientes", (string)null);
                });

            modelBuilder.Entity("FGT.Entidades.Base.Empresa", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long?>("AlteradoPorUsuarioId")
                        .HasColumnType("bigint")
                        .HasColumnName("alterado_por_usuario_id");

                    b.Property<bool>("Ativo")
                        .HasColumnType("boolean")
                        .HasColumnName("ativo");

                    b.Property<string>("Bairro")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("bairro");

                    b.Property<string>("CEP")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("cep");

                    b.Property<string>("Celular")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("celular");

                    b.Property<string>("Cidade")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("cidade");

                    b.Property<string>("Cnpj")
                        .HasMaxLength(18)
                        .HasColumnType("character varying(18)")
                        .HasColumnName("cnpj");

                    b.Property<string>("Complemento")
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("complemento");

                    b.Property<long?>("CriadoPorUsuarioId")
                        .HasColumnType("bigint")
                        .HasColumnName("criado_por_usuario_id");

                    b.Property<DateTime>("DataAlteracao")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("data_alteracao");

                    b.Property<DateTime>("DataCadastro")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("data_cadastro");

                    b.Property<string>("Email")
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("email");

                    b.Property<long?>("EmpresaId")
                        .HasColumnType("bigint")
                        .HasColumnName("empresa_id");

                    b.Property<string>("Endereco")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("endereco");

                    b.Property<int>("Estado")
                        .HasColumnType("integer")
                        .HasColumnName("estado");

                    b.Property<long>("IdEmpresa")
                        .HasColumnType("bigint")
                        .HasColumnName("id_empresa");

                    b.Property<string>("Numero")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("numero");

                    b.Property<string>("Observacoes")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("observacoes");

                    b.Property<string>("RazaoSocial")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)")
                        .HasColumnName("razao_social");

                    b.Property<string>("Telefone")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("telefone");

                    b.HasKey("Id")
                        .HasName("pk_empresas");

                    b.HasIndex("EmpresaId");

                    b.ToTable("empresas", (string)null);
                });

            modelBuilder.Entity("FGT.Entidades.Base.ReportTemplateEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long?>("AlteradoPorUsuarioId")
                        .HasColumnType("bigint")
                        .HasColumnName("alterado_por_usuario_id");

                    b.Property<bool>("Ativo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("ativo");

                    b.Property<long?>("CriadoPorUsuarioId")
                        .HasColumnType("bigint")
                        .HasColumnName("criado_por_usuario_id");

                    b.Property<DateTime>("DataAlteracao")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("data_alteracao");

                    b.Property<DateTime>("DataCadastro")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("data_cadastro");

                    b.Property<string>("Descricao")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("descricao");

                    b.Property<long?>("EmpresaId")
                        .HasColumnType("bigint")
                        .HasColumnName("empresa_id");

                    b.Property<long>("IdEmpresa")
                        .HasColumnType("bigint")
                        .HasColumnName("id_empresa");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("nome");

                    b.Property<bool>("Padrao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("padrao");

                    b.Property<string>("TemplateJson")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("template_json");

                    b.Property<string>("TipoEntidade")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("tipo_entidade");

                    b.HasKey("Id")
                        .HasName("pk_report_templates");

                    b.HasIndex("EmpresaId");

                    b.HasIndex("TipoEntidade");

                    b.HasIndex("TipoEntidade", "Padrao");

                    b.ToTable("report_templates", (string)null);
                });

            modelBuilder.Entity("FGT.Entidades.Base.Usuario", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long?>("AlteradoPorUsuarioId")
                        .HasColumnType("bigint")
                        .HasColumnName("alterado_por_usuario_id");

                    b.Property<bool>("Ativo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("ativo");

                    b.Property<string>("Cpf")
                        .HasMaxLength(14)
                        .HasColumnType("character varying(14)")
                        .HasColumnName("cpf");

                    b.Property<long?>("CriadoPorUsuarioId")
                        .HasColumnType("bigint")
                        .HasColumnName("criado_por_usuario_id");

                    b.Property<DateTime>("DataAlteracao")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("data_alteracao");

                    b.Property<DateTime>("DataCadastro")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("data_cadastro");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("email");

                    b.Property<long>("IdEmpresa")
                        .HasColumnType("bigint")
                        .HasColumnName("id_empresa");

                    b.Property<long?>("IdEmpresaCliente")
                        .HasColumnType("bigint")
                        .HasColumnName("id_empresa_cliente");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)")
                        .HasColumnName("nome");

                    b.Property<string>("Observacoes")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("observacoes");

                    b.Property<int>("Perfil")
                        .HasColumnType("integer")
                        .HasColumnName("perfil");

                    b.Property<string>("SenhaHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("senha_hash");

                    b.Property<string>("Telefone")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("telefone");

                    b.Property<DateTime?>("UltimoLogin")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("ultimo_login");

                    b.HasKey("Id")
                        .HasName("pk_usuarios");

                    b.HasIndex("IdEmpresa");

                    b.HasIndex("IdEmpresaCliente")
                        .IsUnique();

                    b.ToTable("usuarios", (string)null);
                });

            modelBuilder.Entity("FGT.Entidades.CNAE", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<decimal?>("AliquotaISS")
                        .HasColumnType("numeric")
                        .HasColumnName("aliquota_iss");

                    b.Property<long?>("AlteradoPorUsuarioId")
                        .HasColumnType("bigint")
                        .HasColumnName("alterado_por_usuario_id");

                    b.Property<bool>("Ativo")
                        .HasColumnType("boolean")
                        .HasColumnName("ativo");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("codigo");

                    b.Property<long?>("CriadoPorUsuarioId")
                        .HasColumnType("bigint")
                        .HasColumnName("criado_por_usuario_id");

                    b.Property<DateTime>("DataAlteracao")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("data_alteracao");

                    b.Property<DateTime>("DataCadastro")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("data_cadastro");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("descricao");

                    b.Property<long?>("EmpresaId")
                        .HasColumnType("bigint")
                        .HasColumnName("empresa_id");

                    b.Property<long>("IdEmpresa")
                        .HasColumnType("bigint")
                        .HasColumnName("id_empresa");

                    b.HasKey("Id")
                        .HasName("pk_cnaes");

                    b.HasIndex("EmpresaId");

                    b.ToTable("cnaes");
                });

            modelBuilder.Entity("FGT.Entidades.CertificadoDigital", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long?>("AlteradoPorUsuarioId")
                        .HasColumnType("bigint")
                        .HasColumnName("alterado_por_usuario_id");

                    b.Property<string>("ArquivoCertificado")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("arquivo_certificado");

                    b.Property<bool>("Ativo")
                        .HasColumnType("boolean")
                        .HasColumnName("ativo");

                    b.Property<long?>("CriadoPorUsuarioId")
                        .HasColumnType("bigint")
                        .HasColumnName("criado_por_usuario_id");

                    b.Property<DateTime>("DataAlteracao")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("data_alteracao");

                    b.Property<DateTime>("DataCadastro")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("data_cadastro");

                    b.Property<DateTime>("DataValidade")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("data_validade");

                    b.Property<long>("EmpresaClienteId")
                        .HasColumnType("bigint")
                        .HasColumnName("empresa_cliente_id");

                    b.Property<long?>("EmpresaId")
                        .HasColumnType("bigint")
                        .HasColumnName("empresa_id");

                    b.Property<long>("IdEmpresa")
                        .HasColumnType("bigint")
                        .HasColumnName("id_empresa");

                    b.Property<string>("Senha")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("senha");

                    b.Property<string>("Titular")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("titular");

                    b.HasKey("Id")
                        .HasName("pk_certificados_digitais");

                    b.HasIndex("EmpresaClienteId");

                    b.HasIndex("EmpresaId");

                    b.ToTable("certificados_digitais");
                });

            modelBuilder.Entity("FGT.Entidades.ContadorResponsavel", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long?>("AlteradoPorUsuarioId")
                        .HasColumnType("bigint")
                        .HasColumnName("alterado_por_usuario_id");

                    b.Property<bool>("Ativo")
                        .HasColumnType("boolean")
                        .HasColumnName("ativo");

                    b.Property<string>("CNPJEscritorio")
                        .HasMaxLength(18)
                        .HasColumnType("character varying(18)")
                        .HasColumnName("cnpjescritorio");

                    b.Property<string>("CPF")
                        .IsRequired()
                        .HasMaxLength(14)
                        .HasColumnType("character varying(14)")
                        .HasColumnName("cpf");

                    b.Property<string>("CRC")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("crc");

                    b.Property<string>("Celular")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("celular");

                    b.Property<long?>("CriadoPorUsuarioId")
                        .HasColumnType("bigint")
                        .HasColumnName("criado_por_usuario_id");

                    b.Property<DateTime>("DataAlteracao")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("data_alteracao");

                    b.Property<DateTime>("DataCadastro")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("data_cadastro");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("email");

                    b.Property<long?>("EmpresaId")
                        .HasColumnType("bigint")
                        .HasColumnName("empresa_id");

                    b.Property<string>("Escritorio")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("escritorio");

                    b.Property<int>("EstadoCRC")
                        .HasColumnType("integer")
                        .HasColumnName("estado_crc");

                    b.Property<long>("IdEmpresa")
                        .HasColumnType("bigint")
                        .HasColumnName("id_empresa");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("nome");

                    b.Property<string>("Observacoes")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("observacoes");

                    b.Property<string>("Telefone")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("telefone");

                    b.HasKey("Id")
                        .HasName("pk_contadores_responsaveis");

                    b.HasIndex("EmpresaId");

                    b.ToTable("contadores_responsaveis");
                });

            modelBuilder.Entity("FGT.Entidades.DadoBancario", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Agencia")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("agencia");

                    b.Property<long?>("AlteradoPorUsuarioId")
                        .HasColumnType("bigint")
                        .HasColumnName("alterado_por_usuario_id");

                    b.Property<bool>("Ativo")
                        .HasColumnType("boolean")
                        .HasColumnName("ativo");

                    b.Property<string>("ChavePix")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("chave_pix");

                    b.Property<string>("CodigoBanco")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)")
                        .HasColumnName("codigo_banco");

                    b.Property<bool>("ContaPrincipal")
                        .HasColumnType("boolean")
                        .HasColumnName("conta_principal");

                    b.Property<long?>("CriadoPorUsuarioId")
                        .HasColumnType("bigint")
                        .HasColumnName("criado_por_usuario_id");

                    b.Property<DateTime>("DataAlteracao")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("data_alteracao");

                    b.Property<DateTime>("DataCadastro")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("data_cadastro");

                    b.Property<string>("DigitoAgencia")
                        .HasMaxLength(2)
                        .HasColumnType("character varying(2)")
                        .HasColumnName("digito_agencia");

                    b.Property<string>("DigitoConta")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("character varying(2)")
                        .HasColumnName("digito_conta");

                    b.Property<long>("EmpresaClienteId")
                        .HasColumnType("bigint")
                        .HasColumnName("empresa_cliente_id");

                    b.Property<long?>("EmpresaId")
                        .HasColumnType("bigint")
                        .HasColumnName("empresa_id");

                    b.Property<long>("IdEmpresa")
                        .HasColumnType("bigint")
                        .HasColumnName("id_empresa");

                    b.Property<string>("NomeBanco")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("nome_banco");

                    b.Property<string>("NumeroConta")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("numero_conta");

                    b.Property<string>("Observacoes")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("observacoes");

                    b.Property<int>("TipoConta")
                        .HasColumnType("integer")
                        .HasColumnName("tipo_conta");

                    b.HasKey("Id")
                        .HasName("pk_dados_bancarios");

                    b.HasIndex("EmpresaClienteId");

                    b.HasIndex("EmpresaId");

                    b.ToTable("dados_bancarios");
                });

            modelBuilder.Entity("FGT.Entidades.EmpresaCliente", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long?>("AlteradoPorUsuarioId")
                        .HasColumnType("bigint")
                        .HasColumnName("alterado_por_usuario_id");

                    b.Property<bool>("Ativo")
                        .HasColumnType("boolean")
                        .HasColumnName("ativo");

                    b.Property<string>("CEP")
                        .HasMaxLength(9)
                        .HasColumnType("character varying(9)")
                        .HasColumnName("cep");

                    b.Property<long?>("CNAEPrincipalId")
                        .HasColumnType("bigint")
                        .HasColumnName("cnaeprincipal_id");

                    b.Property<string>("CNPJ")
                        .IsRequired()
                        .HasMaxLength(18)
                        .HasColumnType("character varying(18)")
                        .HasColumnName("cnpj");

                    b.Property<string>("Cidade")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("cidade");

                    b.Property<string>("Complemento")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("complemento");

                    b.Property<long?>("ContadorResponsavelId")
                        .HasColumnType("bigint")
                        .HasColumnName("contador_responsavel_id");

                    b.Property<long?>("CriadoPorUsuarioId")
                        .HasColumnType("bigint")
                        .HasColumnName("criado_por_usuario_id");

                    b.Property<DateTime>("DataAlteracao")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("data_alteracao");

                    b.Property<DateTime>("DataCadastro")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("data_cadastro");

                    b.Property<string>("Email")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("email");

                    b.Property<long?>("EmpresaId")
                        .HasColumnType("bigint")
                        .HasColumnName("empresa_id");

                    b.Property<string>("Endereco")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("endereco");

                    b.Property<int>("Estado")
                        .HasColumnType("integer")
                        .HasColumnName("estado");

                    b.Property<long>("IdEmpresa")
                        .HasColumnType("bigint")
                        .HasColumnName("id_empresa");

                    b.Property<string>("InscricaoEstadual")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("inscricao_estadual");

                    b.Property<string>("InscricaoMunicipal")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("inscricao_municipal");

                    b.Property<string>("NomeFantasia")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("nome_fantasia");

                    b.Property<string>("Numero")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("numero");

                    b.Property<string>("Observacoes")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("observacoes");

                    b.Property<string>("RazaoSocial")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("razao_social");

                    b.Property<int>("RegimeTributario")
                        .HasColumnType("integer")
                        .HasColumnName("regime_tributario");

                    b.Property<string>("Telefone")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("telefone");

                    b.HasKey("Id")
                        .HasName("pk_empresas_clientes");

                    b.HasIndex("CNAEPrincipalId");

                    b.HasIndex("ContadorResponsavelId");

                    b.HasIndex("EmpresaId");

                    b.ToTable("empresas_clientes");
                });

            modelBuilder.Entity("FGT.Entidades.Fiscal.NegociacaoFiscal", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long?>("AlteradoPorUsuarioId")
                        .HasColumnType("bigint")
                        .HasColumnName("alterado_por_usuario_id");

                    b.Property<bool>("Ativo")
                        .HasColumnType("boolean")
                        .HasColumnName("ativo");

                    b.Property<string>("CpfCnpjOptante")
                        .IsRequired()
                        .HasMaxLength(18)
                        .HasColumnType("character varying(18)")
                        .HasColumnName("cpf_cnpj_optante");

                    b.Property<long?>("CriadoPorUsuarioId")
                        .HasColumnType("bigint")
                        .HasColumnName("criado_por_usuario_id");

                    b.Property<DateTime>("DataAlteracao")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("data_alteracao");

                    b.Property<DateTime>("DataCadastro")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("data_cadastro");

                    b.Property<long?>("EmpresaId")
                        .HasColumnType("bigint")
                        .HasColumnName("empresa_id");

                    b.Property<long>("IdEmpresa")
                        .HasColumnType("bigint")
                        .HasColumnName("id_empresa");

                    b.Property<string>("MesAnoRequerimento")
                        .IsRequired()
                        .HasMaxLength(7)
                        .HasColumnType("character varying(7)")
                        .HasColumnName("mes_ano_requerimento");

                    b.Property<string>("ModalidadeNegociacao")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("modalidade_negociacao");

                    b.Property<string>("NomeOptante")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("nome_optante");

                    b.Property<string>("NumeroContaNegociacao")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("numero_conta_negociacao");

                    b.Property<int?>("QtdeParcelasAtraso")
                        .HasColumnType("integer")
                        .HasColumnName("qtde_parcelas_atraso");

                    b.Property<int?>("QtdeParcelasConcedidas")
                        .HasColumnType("integer")
                        .HasColumnName("qtde_parcelas_concedidas");

                    b.Property<string>("SituacaoNegociacao")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("situacao_negociacao");

                    b.Property<string>("TipoNegociacao")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("tipo_negociacao");

                    b.Property<string>("UFOptante")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("character varying(2)")
                        .HasColumnName("ufoptante");

                    b.Property<decimal?>("ValorConsolidado")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("valor_consolidado");

                    b.Property<decimal?>("ValorEncargoLegal")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("valor_encargo_legal");

                    b.Property<decimal?>("ValorJuros")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("valor_juros");

                    b.Property<decimal?>("ValorMulta")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("valor_multa");

                    b.Property<decimal?>("ValorPrincipal")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("valor_principal");

                    b.HasKey("Id")
                        .HasName("pk_negociacoes_fiscais");

                    b.HasIndex("EmpresaId");

                    b.ToTable("negociacoes_fiscais");
                });

            modelBuilder.Entity("FGT.Entidades.LancamentoContabil", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long?>("AlteradoPorUsuarioId")
                        .HasColumnType("bigint")
                        .HasColumnName("alterado_por_usuario_id");

                    b.Property<bool>("Ativo")
                        .HasColumnType("boolean")
                        .HasColumnName("ativo");

                    b.Property<string>("Complemento")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("complemento");

                    b.Property<bool>("Conciliado")
                        .HasColumnType("boolean")
                        .HasColumnName("conciliado");

                    b.Property<long>("ContaCreditoId")
                        .HasColumnType("bigint")
                        .HasColumnName("conta_credito_id");

                    b.Property<long>("ContaDebitoId")
                        .HasColumnType("bigint")
                        .HasColumnName("conta_debito_id");

                    b.Property<long?>("CriadoPorUsuarioId")
                        .HasColumnType("bigint")
                        .HasColumnName("criado_por_usuario_id");

                    b.Property<DateTime>("DataAlteracao")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("data_alteracao");

                    b.Property<DateTime>("DataCadastro")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("data_cadastro");

                    b.Property<DateTime?>("DataConciliacao")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("data_conciliacao");

                    b.Property<DateTime>("DataLancamento")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("data_lancamento");

                    b.Property<long>("EmpresaClienteId")
                        .HasColumnType("bigint")
                        .HasColumnName("empresa_cliente_id");

                    b.Property<long?>("EmpresaId")
                        .HasColumnType("bigint")
                        .HasColumnName("empresa_id");

                    b.Property<string>("Historico")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("historico");

                    b.Property<long>("IdEmpresa")
                        .HasColumnType("bigint")
                        .HasColumnName("id_empresa");

                    b.Property<long?>("NotaFiscalId")
                        .HasColumnType("bigint")
                        .HasColumnName("nota_fiscal_id");

                    b.Property<string>("NumeroDocumento")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("numero_documento");

                    b.Property<long?>("PlanoContasId")
                        .HasColumnType("bigint");

                    b.Property<int>("TipoLancamento")
                        .HasColumnType("integer")
                        .HasColumnName("tipo_lancamento");

                    b.Property<decimal>("Valor")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("valor");

                    b.HasKey("Id")
                        .HasName("pk_lancamentos_contabeis");

                    b.HasIndex("ContaCreditoId");

                    b.HasIndex("ContaDebitoId");

                    b.HasIndex("EmpresaClienteId");

                    b.HasIndex("EmpresaId");

                    b.HasIndex("NotaFiscalId");

                    b.HasIndex("PlanoContasId");

                    b.ToTable("lancamentos_contabeis");
                });

            modelBuilder.Entity("FGT.Entidades.NotaFiscal", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long?>("AlteradoPorUsuarioId")
                        .HasColumnType("bigint")
                        .HasColumnName("alterado_por_usuario_id");

                    b.Property<string>("ArquivoPDF")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("arquivo_pdf");

                    b.Property<string>("ArquivoXML")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("arquivo_xml");

                    b.Property<bool>("Ativo")
                        .HasColumnType("boolean")
                        .HasColumnName("ativo");

                    b.Property<string>("ChaveAcesso")
                        .HasMaxLength(44)
                        .HasColumnType("character varying(44)")
                        .HasColumnName("chave_acesso");

                    b.Property<long?>("CriadoPorUsuarioId")
                        .HasColumnType("bigint")
                        .HasColumnName("criado_por_usuario_id");

                    b.Property<DateTime>("DataAlteracao")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("data_alteracao");

                    b.Property<DateTime>("DataCadastro")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("data_cadastro");

                    b.Property<DateTime?>("DataEmissao")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("data_emissao");

                    b.Property<DateTime?>("DataSaidaEntrada")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("data_saida_entrada");

                    b.Property<long>("EmpresaClienteId")
                        .HasColumnType("bigint")
                        .HasColumnName("empresa_cliente_id");

                    b.Property<long?>("EmpresaId")
                        .HasColumnType("bigint")
                        .HasColumnName("empresa_id");

                    b.Property<long>("IdEmpresa")
                        .HasColumnType("bigint")
                        .HasColumnName("id_empresa");

                    b.Property<int>("Modelo")
                        .HasColumnType("integer")
                        .HasColumnName("modelo");

                    b.Property<int>("Numero")
                        .HasColumnType("integer")
                        .HasColumnName("numero");

                    b.Property<string>("Observacoes")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("observacoes");

                    b.Property<int>("Serie")
                        .HasColumnType("integer")
                        .HasColumnName("serie");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<int>("Tipo")
                        .HasColumnType("integer")
                        .HasColumnName("tipo");

                    b.Property<decimal>("ValorCOFINS")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("valor_cofins");

                    b.Property<decimal>("ValorICMS")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("valor_icms");

                    b.Property<decimal>("ValorIPI")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("valor_ipi");

                    b.Property<decimal>("ValorPIS")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("valor_pis");

                    b.Property<decimal>("ValorProdutos")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("valor_produtos");

                    b.Property<decimal>("ValorServicos")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("valor_servicos");

                    b.Property<decimal>("ValorTotal")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("valor_total");

                    b.HasKey("Id")
                        .HasName("pk_notas_fiscais");

                    b.HasIndex("EmpresaClienteId");

                    b.HasIndex("EmpresaId");

                    b.ToTable("notas_fiscais");
                });

            modelBuilder.Entity("FGT.Entidades.NotaFiscalItem", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long?>("AlteradoPorUsuarioId")
                        .HasColumnType("bigint")
                        .HasColumnName("alterado_por_usuario_id");

                    b.Property<bool>("Ativo")
                        .HasColumnType("boolean")
                        .HasColumnName("ativo");

                    b.Property<string>("CFOP")
                        .HasMaxLength(4)
                        .HasColumnType("character varying(4)")
                        .HasColumnName("cfop");

                    b.Property<string>("Codigo")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("codigo");

                    b.Property<long?>("CriadoPorUsuarioId")
                        .HasColumnType("bigint")
                        .HasColumnName("criado_por_usuario_id");

                    b.Property<DateTime>("DataAlteracao")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("data_alteracao");

                    b.Property<DateTime>("DataCadastro")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("data_cadastro");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("descricao");

                    b.Property<long?>("EmpresaId")
                        .HasColumnType("bigint")
                        .HasColumnName("empresa_id");

                    b.Property<long>("IdEmpresa")
                        .HasColumnType("bigint")
                        .HasColumnName("id_empresa");

                    b.Property<string>("NCM")
                        .HasMaxLength(8)
                        .HasColumnType("character varying(8)")
                        .HasColumnName("ncm");

                    b.Property<long>("NotaFiscalId")
                        .HasColumnType("bigint")
                        .HasColumnName("nota_fiscal_id");

                    b.Property<decimal>("Quantidade")
                        .HasColumnType("decimal(18,4)")
                        .HasColumnName("quantidade");

                    b.Property<decimal>("ValorTotal")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("valor_total");

                    b.Property<decimal>("ValorUnitario")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("valor_unitario");

                    b.HasKey("Id")
                        .HasName("pk_notas_fiscais_itens");

                    b.HasIndex("EmpresaId");

                    b.HasIndex("NotaFiscalId");

                    b.ToTable("notas_fiscais_itens");
                });

            modelBuilder.Entity("FGT.Entidades.ObrigacaoFiscal", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long?>("AlteradoPorUsuarioId")
                        .HasColumnType("bigint")
                        .HasColumnName("alterado_por_usuario_id");

                    b.Property<string>("ArquivoEnviado")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("arquivo_enviado");

                    b.Property<string>("ArquivoRecibo")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("arquivo_recibo");

                    b.Property<bool>("Ativo")
                        .HasColumnType("boolean")
                        .HasColumnName("ativo");

                    b.Property<DateTime>("Competencia")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("competencia");

                    b.Property<long?>("CriadoPorUsuarioId")
                        .HasColumnType("bigint")
                        .HasColumnName("criado_por_usuario_id");

                    b.Property<DateTime>("DataAlteracao")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("data_alteracao");

                    b.Property<DateTime>("DataCadastro")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("data_cadastro");

                    b.Property<DateTime?>("DataEntrega")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("data_entrega");

                    b.Property<DateTime>("DataVencimento")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("data_vencimento");

                    b.Property<long>("EmpresaClienteId")
                        .HasColumnType("bigint")
                        .HasColumnName("empresa_cliente_id");

                    b.Property<long?>("EmpresaId")
                        .HasColumnType("bigint")
                        .HasColumnName("empresa_id");

                    b.Property<long>("IdEmpresa")
                        .HasColumnType("bigint")
                        .HasColumnName("id_empresa");

                    b.Property<string>("NumeroRecibo")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("numero_recibo");

                    b.Property<string>("Observacoes")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("observacoes");

                    b.Property<int>("Periodicidade")
                        .HasColumnType("integer")
                        .HasColumnName("periodicidade");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<int>("TipoObrigacao")
                        .HasColumnType("integer")
                        .HasColumnName("tipo_obrigacao");

                    b.HasKey("Id")
                        .HasName("pk_obrigacoes_fiscais");

                    b.HasIndex("EmpresaClienteId");

                    b.HasIndex("EmpresaId");

                    b.ToTable("obrigacoes_fiscais");
                });

            modelBuilder.Entity("FGT.Entidades.ParametroFiscal", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long?>("AlteradoPorUsuarioId")
                        .HasColumnType("bigint")
                        .HasColumnName("alterado_por_usuario_id");

                    b.Property<int>("AmbienteNFe")
                        .HasColumnType("integer")
                        .HasColumnName("ambiente_nfe");

                    b.Property<bool>("Ativo")
                        .HasColumnType("boolean")
                        .HasColumnName("ativo");

                    b.Property<string>("CfopPadraoCompra")
                        .HasMaxLength(6)
                        .HasColumnType("character varying(6)")
                        .HasColumnName("cfop_padrao_compra");

                    b.Property<string>("CfopPadraoServico")
                        .HasMaxLength(6)
                        .HasColumnType("character varying(6)")
                        .HasColumnName("cfop_padrao_servico");

                    b.Property<string>("CfopPadraoVenda")
                        .HasMaxLength(6)
                        .HasColumnType("character varying(6)")
                        .HasColumnName("cfop_padrao_venda");

                    b.Property<long?>("CriadoPorUsuarioId")
                        .HasColumnType("bigint")
                        .HasColumnName("criado_por_usuario_id");

                    b.Property<string>("CstCofinsPadrao")
                        .HasMaxLength(2)
                        .HasColumnType("character varying(2)")
                        .HasColumnName("cst_cofins_padrao");

                    b.Property<string>("CstIcmsPadrao")
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)")
                        .HasColumnName("cst_icms_padrao");

                    b.Property<string>("CstPisPadrao")
                        .HasMaxLength(2)
                        .HasColumnType("character varying(2)")
                        .HasColumnName("cst_pis_padrao");

                    b.Property<DateTime>("DataAlteracao")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("data_alteracao");

                    b.Property<DateTime>("DataCadastro")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("data_cadastro");

                    b.Property<string>("EmailPadraoCopia")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("email_padrao_copia");

                    b.Property<long>("EmpresaClienteId")
                        .HasColumnType("bigint")
                        .HasColumnName("empresa_cliente_id");

                    b.Property<long?>("EmpresaId")
                        .HasColumnType("bigint")
                        .HasColumnName("empresa_id");

                    b.Property<bool>("EnviarEmailAutomatico")
                        .HasColumnType("boolean")
                        .HasColumnName("enviar_email_automatico");

                    b.Property<long>("IdEmpresa")
                        .HasColumnType("bigint")
                        .HasColumnName("id_empresa");

                    b.Property<string>("MensagemPadraoNFSe")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("mensagem_padrao_nfse");

                    b.Property<string>("MensagemPadraoNFe")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("mensagem_padrao_nfe");

                    b.Property<int>("ProximoNumeroNFSe")
                        .HasColumnType("integer")
                        .HasColumnName("proximo_numero_nfse");

                    b.Property<int>("ProximoNumeroNFe")
                        .HasColumnType("integer")
                        .HasColumnName("proximo_numero_nfe");

                    b.Property<int>("SerieNFSe")
                        .HasColumnType("integer")
                        .HasColumnName("serie_nfse");

                    b.Property<int>("SerieNFe")
                        .HasColumnType("integer")
                        .HasColumnName("serie_nfe");

                    b.HasKey("Id")
                        .HasName("pk_parametros_fiscais");

                    b.HasIndex("EmpresaClienteId");

                    b.HasIndex("EmpresaId");

                    b.ToTable("parametros_fiscais");
                });

            modelBuilder.Entity("FGT.Entidades.PlanoContas", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<bool>("AceitaLancamento")
                        .HasColumnType("boolean")
                        .HasColumnName("aceita_lancamento");

                    b.Property<long?>("AlteradoPorUsuarioId")
                        .HasColumnType("bigint")
                        .HasColumnName("alterado_por_usuario_id");

                    b.Property<bool>("Ativo")
                        .HasColumnType("boolean")
                        .HasColumnName("ativo");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("codigo");

                    b.Property<bool>("ContaAnalitica")
                        .HasColumnType("boolean")
                        .HasColumnName("conta_analitica");

                    b.Property<long?>("ContaPaiId")
                        .HasColumnType("bigint")
                        .HasColumnName("conta_pai_id");

                    b.Property<long?>("CriadoPorUsuarioId")
                        .HasColumnType("bigint")
                        .HasColumnName("criado_por_usuario_id");

                    b.Property<DateTime>("DataAlteracao")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("data_alteracao");

                    b.Property<DateTime>("DataCadastro")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("data_cadastro");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("descricao");

                    b.Property<long?>("EmpresaId")
                        .HasColumnType("bigint")
                        .HasColumnName("empresa_id");

                    b.Property<bool>("ExibirNaDRE")
                        .HasColumnType("boolean")
                        .HasColumnName("exibir_na_dre");

                    b.Property<bool>("ExibirNoBalancete")
                        .HasColumnType("boolean")
                        .HasColumnName("exibir_no_balancete");

                    b.Property<long>("IdEmpresa")
                        .HasColumnType("bigint")
                        .HasColumnName("id_empresa");

                    b.Property<int>("Natureza")
                        .HasColumnType("integer")
                        .HasColumnName("natureza");

                    b.Property<int>("Nivel")
                        .HasColumnType("integer")
                        .HasColumnName("nivel");

                    b.Property<string>("Observacoes")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("observacoes");

                    b.Property<int>("TipoConta")
                        .HasColumnType("integer")
                        .HasColumnName("tipo_conta");

                    b.HasKey("Id")
                        .HasName("pk_plano_contas");

                    b.HasIndex("ContaPaiId");

                    b.HasIndex("EmpresaId");

                    b.ToTable("plano_contas");
                });

            modelBuilder.Entity("FGT.Entidades.Processing.ImportacaoNegociacaoFiscal", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long?>("AlteradoPorUsuarioId")
                        .HasColumnType("bigint")
                        .HasColumnName("alterado_por_usuario_id");

                    b.Property<string>("ArquivoExcel")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("arquivo_excel");

                    b.Property<bool>("Ativo")
                        .HasColumnType("boolean")
                        .HasColumnName("ativo");

                    b.Property<long?>("CriadoPorUsuarioId")
                        .HasColumnType("bigint")
                        .HasColumnName("criado_por_usuario_id");

                    b.Property<DateTime>("DataAlteracao")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("data_alteracao");

                    b.Property<DateTime>("DataCadastro")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("data_cadastro");

                    b.Property<string>("Descricao")
                        .HasColumnType("text")
                        .HasColumnName("descricao");

                    b.Property<long?>("EmpresaId")
                        .HasColumnType("bigint")
                        .HasColumnName("empresa_id");

                    b.Property<long>("IdEmpresa")
                        .HasColumnType("bigint")
                        .HasColumnName("id_empresa");

                    b.HasKey("Id")
                        .HasName("pk_importacoes_negociacoes_fiscais");

                    b.HasIndex("EmpresaId");

                    b.ToTable("importacoes_negociacoes_fiscais");
                });

            modelBuilder.Entity("FGT.Entidades.UsuarioEmpresaCliente", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<bool>("Ativo")
                        .HasColumnType("boolean")
                        .HasColumnName("ativo");

                    b.Property<DateTime>("DataVinculo")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("data_vinculo");

                    b.Property<long>("IdEmpresa")
                        .HasColumnType("bigint")
                        .HasColumnName("id_empresa");

                    b.Property<long>("IdEmpresaCliente")
                        .HasColumnType("bigint")
                        .HasColumnName("id_empresa_cliente");

                    b.Property<long>("IdUsuario")
                        .HasColumnType("bigint")
                        .HasColumnName("id_usuario");

                    b.HasKey("Id")
                        .HasName("pk_usuario_empresa_cliente");

                    b.HasIndex("IdEmpresa");

                    b.HasIndex("IdEmpresaCliente");

                    b.HasIndex("IdUsuario");

                    b.ToTable("usuario_empresa_cliente");
                });

            modelBuilder.Entity("FGT.Entidades.AliquotaImposto", b =>
                {
                    b.HasOne("FGT.Entidades.Base.Empresa", "Empresa")
                        .WithMany()
                        .HasForeignKey("EmpresaId");

                    b.Navigation("Empresa");
                });

            modelBuilder.Entity("FGT.Entidades.Base.AuditLog", b =>
                {
                    b.HasOne("FGT.Entidades.Base.Empresa", "Empresa")
                        .WithMany()
                        .HasForeignKey("IdEmpresa")
                        .OnDelete(DeleteBehavior.SetNull)
                        .IsRequired();

                    b.HasOne("FGT.Entidades.Base.Usuario", "Usuario")
                        .WithMany("AuditLogs")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Empresa");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("FGT.Entidades.Base.Cliente", b =>
                {
                    b.HasOne("FGT.Entidades.Base.Empresa", "Empresa")
                        .WithMany()
                        .HasForeignKey("EmpresaId");

                    b.Navigation("Empresa");
                });

            modelBuilder.Entity("FGT.Entidades.Base.Empresa", b =>
                {
                    b.HasOne("FGT.Entidades.Base.Empresa", "Empresa")
                        .WithMany()
                        .HasForeignKey("EmpresaId");

                    b.Navigation("Empresa");
                });

            modelBuilder.Entity("FGT.Entidades.Base.ReportTemplateEntity", b =>
                {
                    b.HasOne("FGT.Entidades.Base.Empresa", "Empresa")
                        .WithMany()
                        .HasForeignKey("EmpresaId");

                    b.Navigation("Empresa");
                });

            modelBuilder.Entity("FGT.Entidades.Base.Usuario", b =>
                {
                    b.HasOne("FGT.Entidades.Base.Empresa", "Empresa")
                        .WithMany()
                        .HasForeignKey("IdEmpresa")
                        .OnDelete(DeleteBehavior.SetNull)
                        .IsRequired();

                    b.HasOne("FGT.Entidades.EmpresaCliente", "EmpresaCliente")
                        .WithOne()
                        .HasForeignKey("FGT.Entidades.Base.Usuario", "IdEmpresaCliente");

                    b.Navigation("Empresa");

                    b.Navigation("EmpresaCliente");
                });

            modelBuilder.Entity("FGT.Entidades.CNAE", b =>
                {
                    b.HasOne("FGT.Entidades.Base.Empresa", "Empresa")
                        .WithMany()
                        .HasForeignKey("EmpresaId");

                    b.Navigation("Empresa");
                });

            modelBuilder.Entity("FGT.Entidades.CertificadoDigital", b =>
                {
                    b.HasOne("FGT.Entidades.EmpresaCliente", "EmpresaCliente")
                        .WithMany("Certificados")
                        .HasForeignKey("EmpresaClienteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FGT.Entidades.Base.Empresa", "Empresa")
                        .WithMany()
                        .HasForeignKey("EmpresaId");

                    b.Navigation("Empresa");

                    b.Navigation("EmpresaCliente");
                });

            modelBuilder.Entity("FGT.Entidades.ContadorResponsavel", b =>
                {
                    b.HasOne("FGT.Entidades.Base.Empresa", "Empresa")
                        .WithMany()
                        .HasForeignKey("EmpresaId");

                    b.Navigation("Empresa");
                });

            modelBuilder.Entity("FGT.Entidades.DadoBancario", b =>
                {
                    b.HasOne("FGT.Entidades.EmpresaCliente", "EmpresaCliente")
                        .WithMany("DadosBancarios")
                        .HasForeignKey("EmpresaClienteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FGT.Entidades.Base.Empresa", "Empresa")
                        .WithMany()
                        .HasForeignKey("EmpresaId");

                    b.Navigation("Empresa");

                    b.Navigation("EmpresaCliente");
                });

            modelBuilder.Entity("FGT.Entidades.EmpresaCliente", b =>
                {
                    b.HasOne("FGT.Entidades.CNAE", "CNAEPrincipal")
                        .WithMany()
                        .HasForeignKey("CNAEPrincipalId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("FGT.Entidades.ContadorResponsavel", "ContadorResponsavel")
                        .WithMany("EmpresasClientes")
                        .HasForeignKey("ContadorResponsavelId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("FGT.Entidades.Base.Empresa", "Empresa")
                        .WithMany()
                        .HasForeignKey("EmpresaId");

                    b.Navigation("CNAEPrincipal");

                    b.Navigation("ContadorResponsavel");

                    b.Navigation("Empresa");
                });

            modelBuilder.Entity("FGT.Entidades.Fiscal.NegociacaoFiscal", b =>
                {
                    b.HasOne("FGT.Entidades.Base.Empresa", "Empresa")
                        .WithMany()
                        .HasForeignKey("EmpresaId");

                    b.Navigation("Empresa");
                });

            modelBuilder.Entity("FGT.Entidades.LancamentoContabil", b =>
                {
                    b.HasOne("FGT.Entidades.PlanoContas", "ContaCredito")
                        .WithMany()
                        .HasForeignKey("ContaCreditoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("FGT.Entidades.PlanoContas", "ContaDebito")
                        .WithMany()
                        .HasForeignKey("ContaDebitoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("FGT.Entidades.EmpresaCliente", "EmpresaCliente")
                        .WithMany("Lancamentos")
                        .HasForeignKey("EmpresaClienteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("FGT.Entidades.Base.Empresa", "Empresa")
                        .WithMany()
                        .HasForeignKey("EmpresaId");

                    b.HasOne("FGT.Entidades.NotaFiscal", "NotaFiscal")
                        .WithMany()
                        .HasForeignKey("NotaFiscalId");

                    b.HasOne("FGT.Entidades.PlanoContas", null)
                        .WithMany("Lancamentos")
                        .HasForeignKey("PlanoContasId");

                    b.Navigation("ContaCredito");

                    b.Navigation("ContaDebito");

                    b.Navigation("Empresa");

                    b.Navigation("EmpresaCliente");

                    b.Navigation("NotaFiscal");
                });

            modelBuilder.Entity("FGT.Entidades.NotaFiscal", b =>
                {
                    b.HasOne("FGT.Entidades.EmpresaCliente", "EmpresaCliente")
                        .WithMany("NotasFiscais")
                        .HasForeignKey("EmpresaClienteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FGT.Entidades.Base.Empresa", "Empresa")
                        .WithMany()
                        .HasForeignKey("EmpresaId");

                    b.Navigation("Empresa");

                    b.Navigation("EmpresaCliente");
                });

            modelBuilder.Entity("FGT.Entidades.NotaFiscalItem", b =>
                {
                    b.HasOne("FGT.Entidades.Base.Empresa", "Empresa")
                        .WithMany()
                        .HasForeignKey("EmpresaId");

                    b.HasOne("FGT.Entidades.NotaFiscal", "NotaFiscal")
                        .WithMany("Itens")
                        .HasForeignKey("NotaFiscalId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Empresa");

                    b.Navigation("NotaFiscal");
                });

            modelBuilder.Entity("FGT.Entidades.ObrigacaoFiscal", b =>
                {
                    b.HasOne("FGT.Entidades.EmpresaCliente", "EmpresaCliente")
                        .WithMany("ObrigacoesFiscais")
                        .HasForeignKey("EmpresaClienteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FGT.Entidades.Base.Empresa", "Empresa")
                        .WithMany()
                        .HasForeignKey("EmpresaId");

                    b.Navigation("Empresa");

                    b.Navigation("EmpresaCliente");
                });

            modelBuilder.Entity("FGT.Entidades.ParametroFiscal", b =>
                {
                    b.HasOne("FGT.Entidades.EmpresaCliente", "EmpresaCliente")
                        .WithMany("ParametrosFiscais")
                        .HasForeignKey("EmpresaClienteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FGT.Entidades.Base.Empresa", "Empresa")
                        .WithMany()
                        .HasForeignKey("EmpresaId");

                    b.Navigation("Empresa");

                    b.Navigation("EmpresaCliente");
                });

            modelBuilder.Entity("FGT.Entidades.PlanoContas", b =>
                {
                    b.HasOne("FGT.Entidades.PlanoContas", "ContaPai")
                        .WithMany("ContasFilhas")
                        .HasForeignKey("ContaPaiId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("FGT.Entidades.Base.Empresa", "Empresa")
                        .WithMany()
                        .HasForeignKey("EmpresaId");

                    b.Navigation("ContaPai");

                    b.Navigation("Empresa");
                });

            modelBuilder.Entity("FGT.Entidades.Processing.ImportacaoNegociacaoFiscal", b =>
                {
                    b.HasOne("FGT.Entidades.Base.Empresa", "Empresa")
                        .WithMany()
                        .HasForeignKey("EmpresaId");

                    b.Navigation("Empresa");
                });

            modelBuilder.Entity("FGT.Entidades.UsuarioEmpresaCliente", b =>
                {
                    b.HasOne("FGT.Entidades.Base.Empresa", "Empresa")
                        .WithMany()
                        .HasForeignKey("IdEmpresa")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FGT.Entidades.EmpresaCliente", "EmpresaCliente")
                        .WithMany()
                        .HasForeignKey("IdEmpresaCliente")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FGT.Entidades.Base.Usuario", "Usuario")
                        .WithMany("EmpresasVinculadas")
                        .HasForeignKey("IdUsuario")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Empresa");

                    b.Navigation("EmpresaCliente");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("FGT.Entidades.Base.Usuario", b =>
                {
                    b.Navigation("AuditLogs");

                    b.Navigation("EmpresasVinculadas");
                });

            modelBuilder.Entity("FGT.Entidades.ContadorResponsavel", b =>
                {
                    b.Navigation("EmpresasClientes");
                });

            modelBuilder.Entity("FGT.Entidades.EmpresaCliente", b =>
                {
                    b.Navigation("Certificados");

                    b.Navigation("DadosBancarios");

                    b.Navigation("Lancamentos");

                    b.Navigation("NotasFiscais");

                    b.Navigation("ObrigacoesFiscais");

                    b.Navigation("ParametrosFiscais");
                });

            modelBuilder.Entity("FGT.Entidades.NotaFiscal", b =>
                {
                    b.Navigation("Itens");
                });

            modelBuilder.Entity("FGT.Entidades.PlanoContas", b =>
                {
                    b.Navigation("ContasFilhas");

                    b.Navigation("Lancamentos");
                });
#pragma warning restore 612, 618
        }
    }
}
