// <auto-generated />
using System;
using AutoGestao.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace AutoGestao.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("AutoGestao.Entidades.AuditLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("AlteradoPorUsuarioId")
                        .HasColumnType("integer")
                        .HasColumnName("alterado_por_usuario_id");

                    b.Property<string>("CamposAlterados")
                        .HasColumnType("text")
                        .HasColumnName("campos_alterados");

                    b.Property<int?>("CriadoPorUsuarioId")
                        .HasColumnType("integer")
                        .HasColumnName("criado_por_usuario_id");

                    b.Property<DateTime>("DataAlteracao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasDefaultValue(new DateTime(2025, 9, 26, 6, 52, 52, 80, DateTimeKind.Utc).AddTicks(5301))
                        .HasColumnName("data_alteracao");

                    b.Property<DateTime>("DataCadastro")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("data_cadastro");

                    b.Property<DateTime>("DataHora")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("data_hora");

                    b.Property<long?>("DuracaoMs")
                        .HasColumnType("bigint")
                        .HasColumnName("duracao_ms");

                    b.Property<string>("EntidadeDisplayName")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("entidade_display_name");

                    b.Property<string>("EntidadeId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("entidade_id");

                    b.Property<string>("EntidadeNome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("entidade_nome");

                    b.Property<string>("IpCliente")
                        .HasMaxLength(45)
                        .HasColumnType("character varying(45)")
                        .HasColumnName("ip_cliente");

                    b.Property<string>("MensagemErro")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("mensagem_erro");

                    b.Property<string>("MetodoHttp")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("metodo_http");

                    b.Property<bool>("Sucesso")
                        .HasColumnType("boolean")
                        .HasColumnName("sucesso");

                    b.Property<string>("TabelaNome")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("tabela_nome");

                    b.Property<int>("TipoOperacao")
                        .HasColumnType("integer")
                        .HasColumnName("tipo_operacao");

                    b.Property<string>("UrlRequisicao")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("url_requisicao");

                    b.Property<string>("UserAgent")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("user_agent");

                    b.Property<string>("UsuarioEmail")
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("usuario_email");

                    b.Property<int?>("UsuarioId")
                        .HasColumnType("integer")
                        .HasColumnName("usuario_id");

                    b.Property<string>("UsuarioNome")
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)")
                        .HasColumnName("usuario_nome");

                    b.Property<string>("ValoresAntigos")
                        .HasColumnType("text")
                        .HasColumnName("valores_antigos");

                    b.Property<string>("ValoresNovos")
                        .HasColumnType("text")
                        .HasColumnName("valores_novos");

                    b.HasKey("Id")
                        .HasName("pk_audit_logs");

                    b.HasIndex("DataHora");

                    b.HasIndex("EntidadeNome");

                    b.HasIndex("TipoOperacao");

                    b.HasIndex("UsuarioId");

                    b.HasIndex("EntidadeNome", "EntidadeId");

                    b.ToTable("audit_logs", (string)null);

                    b.HasDiscriminator().HasValue("AuditLog");
                });

            modelBuilder.Entity("AutoGestao.Entidades.Avaliacao", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("AlteradoPorUsuarioId")
                        .HasColumnType("integer")
                        .HasColumnName("alterado_por_usuario_id");

                    b.Property<int>("AnoVeiculo")
                        .HasColumnType("integer")
                        .HasColumnName("ano_veiculo");

                    b.Property<int?>("ClienteId")
                        .HasColumnType("integer")
                        .HasColumnName("cliente_id");

                    b.Property<int?>("CriadoPorUsuarioId")
                        .HasColumnType("integer")
                        .HasColumnName("criado_por_usuario_id");

                    b.Property<DateTime>("DataAlteracao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasDefaultValue(new DateTime(2025, 9, 26, 6, 52, 52, 76, DateTimeKind.Utc).AddTicks(9075))
                        .HasColumnName("data_alteracao");

                    b.Property<DateTime>("DataAvaliacao")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("data_avaliacao");

                    b.Property<DateTime>("DataCadastro")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("data_cadastro");

                    b.Property<string>("Observacoes")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("observacoes");

                    b.Property<string>("PlacaVeiculo")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("placa_veiculo");

                    b.Property<int>("StatusAvaliacao")
                        .HasColumnType("integer")
                        .HasColumnName("status_avaliacao");

                    b.Property<decimal?>("ValorOferecido")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("valor_oferecido");

                    b.Property<int?>("VeiculoMarcaId")
                        .HasColumnType("integer")
                        .HasColumnName("veiculo_marca_id");

                    b.Property<int?>("VeiculoMarcaModeloId")
                        .HasColumnType("integer")
                        .HasColumnName("veiculo_marca_modelo_id");

                    b.Property<int?>("VendedorResponsavelId")
                        .HasColumnType("integer")
                        .HasColumnName("vendedor_responsavel_id");

                    b.HasKey("Id")
                        .HasName("pk_avaliacoes");

                    b.HasIndex("ClienteId");

                    b.HasIndex("DataAvaliacao");

                    b.HasIndex("StatusAvaliacao");

                    b.HasIndex("VeiculoMarcaId");

                    b.HasIndex("VeiculoMarcaModeloId");

                    b.HasIndex("VendedorResponsavelId");

                    b.ToTable("avaliacoes", (string)null);

                    b.HasDiscriminator().HasValue("Avaliacao");
                });

            modelBuilder.Entity("AutoGestao.Entidades.Cliente", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("AlteradoPorUsuarioId")
                        .HasColumnType("integer")
                        .HasColumnName("alterado_por_usuario_id");

                    b.Property<bool>("Ativo")
                        .HasColumnType("boolean")
                        .HasColumnName("ativo");

                    b.Property<string>("Bairro")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("bairro");

                    b.Property<string>("CEP")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("cep");

                    b.Property<string>("CNPJ")
                        .HasMaxLength(18)
                        .HasColumnType("character varying(18)")
                        .HasColumnName("cnpj");

                    b.Property<string>("CPF")
                        .HasMaxLength(14)
                        .HasColumnType("character varying(14)")
                        .HasColumnName("cpf");

                    b.Property<string>("Celular")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("celular");

                    b.Property<string>("Cidade")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("cidade");

                    b.Property<string>("Complemento")
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("complemento");

                    b.Property<int?>("CriadoPorUsuarioId")
                        .HasColumnType("integer")
                        .HasColumnName("criado_por_usuario_id");

                    b.Property<DateTime>("DataAlteracao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasDefaultValue(new DateTime(2025, 9, 26, 6, 52, 52, 72, DateTimeKind.Utc).AddTicks(8802))
                        .HasColumnName("data_alteracao");

                    b.Property<DateTime>("DataCadastro")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("data_cadastro");

                    b.Property<DateTime?>("DataNascimento")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("data_nascimento");

                    b.Property<string>("Email")
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("email");

                    b.Property<string>("Endereco")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("endereco");

                    b.Property<int>("Estado")
                        .HasColumnType("integer")
                        .HasColumnName("estado");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)")
                        .HasColumnName("nome");

                    b.Property<string>("Numero")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("numero");

                    b.Property<string>("Observacoes")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("observacoes");

                    b.Property<string>("RG")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("rg");

                    b.Property<string>("Telefone")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("telefone");

                    b.Property<int>("TipoCliente")
                        .HasColumnType("integer")
                        .HasColumnName("tipo_cliente");

                    b.HasKey("Id")
                        .HasName("pk_clientes");

                    b.HasIndex("AlteradoPorUsuarioId");

                    b.HasIndex("CNPJ")
                        .IsUnique()
                        .HasFilter("cnpj IS NOT NULL");

                    b.HasIndex("CPF")
                        .IsUnique()
                        .HasFilter("cpf IS NOT NULL");

                    b.HasIndex("CriadoPorUsuarioId");

                    b.HasIndex("Email")
                        .HasDatabaseName("ix_cliente_email");

                    b.HasIndex("Nome")
                        .HasDatabaseName("ix_cliente_nome");

                    b.ToTable("clientes", (string)null);

                    b.HasDiscriminator().HasValue("Cliente");
                });

            modelBuilder.Entity("AutoGestao.Entidades.Despesa", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("AlteradoPorUsuarioId")
                        .HasColumnType("integer")
                        .HasColumnName("alterado_por_usuario_id");

                    b.Property<int?>("CriadoPorUsuarioId")
                        .HasColumnType("integer")
                        .HasColumnName("criado_por_usuario_id");

                    b.Property<DateTime>("DataAlteracao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasDefaultValue(new DateTime(2025, 9, 26, 6, 52, 52, 77, DateTimeKind.Utc).AddTicks(3223))
                        .HasColumnName("data_alteracao");

                    b.Property<DateTime>("DataCadastro")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("data_cadastro");

                    b.Property<DateTime>("DataDespesa")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("data_despesa");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("descricao");

                    b.Property<int>("DespesaTipoId")
                        .HasColumnType("integer")
                        .HasColumnName("despesa_tipo_id");

                    b.Property<int>("FornecedorId")
                        .HasColumnType("integer")
                        .HasColumnName("fornecedor_id");

                    b.Property<string>("NumeroNF")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("numero_nf");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<decimal>("Valor")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("valor");

                    b.Property<int>("VeiculoId")
                        .HasColumnType("integer")
                        .HasColumnName("veiculo_id");

                    b.HasKey("Id")
                        .HasName("pk_despesas");

                    b.HasIndex("DataDespesa");

                    b.HasIndex("DespesaTipoId");

                    b.HasIndex("FornecedorId");

                    b.HasIndex("Status");

                    b.HasIndex("VeiculoId");

                    b.ToTable("despesas", (string)null);

                    b.HasDiscriminator().HasValue("Despesa");
                });

            modelBuilder.Entity("AutoGestao.Entidades.DespesaTipo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("AlteradoPorUsuarioId")
                        .HasColumnType("integer")
                        .HasColumnName("alterado_por_usuario_id");

                    b.Property<int?>("CriadoPorUsuarioId")
                        .HasColumnType("integer")
                        .HasColumnName("criado_por_usuario_id");

                    b.Property<DateTime>("DataAlteracao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasDefaultValue(new DateTime(2025, 9, 26, 6, 52, 52, 77, DateTimeKind.Utc).AddTicks(7374))
                        .HasColumnName("data_alteracao");

                    b.Property<DateTime>("DataCadastro")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("data_cadastro");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("descricao");

                    b.HasKey("Id")
                        .HasName("pk_despesa_tipos");

                    b.HasIndex("Descricao")
                        .IsUnique();

                    b.ToTable("despesa_tipos", (string)null);

                    b.HasDiscriminator().HasValue("DespesaTipo");
                });

            modelBuilder.Entity("AutoGestao.Entidades.Fornecedor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("AlteradoPorUsuarioId")
                        .HasColumnType("integer")
                        .HasColumnName("alterado_por_usuario_id");

                    b.Property<bool>("Ativo")
                        .HasColumnType("boolean")
                        .HasColumnName("ativo");

                    b.Property<string>("Bairro")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("bairro");

                    b.Property<string>("CEP")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("cep");

                    b.Property<string>("CNPJ")
                        .HasMaxLength(18)
                        .HasColumnType("character varying(18)")
                        .HasColumnName("cnpj");

                    b.Property<string>("CPF")
                        .HasMaxLength(14)
                        .HasColumnType("character varying(14)")
                        .HasColumnName("cpf");

                    b.Property<string>("Celular")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("celular");

                    b.Property<string>("Cidade")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("cidade");

                    b.Property<string>("Complemento")
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("complemento");

                    b.Property<int?>("CriadoPorUsuarioId")
                        .HasColumnType("integer")
                        .HasColumnName("criado_por_usuario_id");

                    b.Property<DateTime>("DataAlteracao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasDefaultValue(new DateTime(2025, 9, 26, 6, 52, 52, 73, DateTimeKind.Utc).AddTicks(5782))
                        .HasColumnName("data_alteracao");

                    b.Property<DateTime>("DataCadastro")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("data_cadastro");

                    b.Property<DateTime?>("DataNascimento")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("data_nascimento");

                    b.Property<string>("Email")
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("email");

                    b.Property<string>("Endereco")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("endereco");

                    b.Property<string>("Estado")
                        .HasMaxLength(2)
                        .HasColumnType("character varying(2)")
                        .HasColumnName("estado");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)")
                        .HasColumnName("nome");

                    b.Property<string>("Numero")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("numero");

                    b.Property<string>("Observacoes")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("observacoes");

                    b.Property<string>("RG")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("rg");

                    b.Property<string>("Telefone")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("telefone");

                    b.Property<int>("TipoFornecedor")
                        .HasColumnType("integer")
                        .HasColumnName("tipo_fornecedor");

                    b.HasKey("Id")
                        .HasName("pk_fornecedores");

                    b.HasIndex("CNPJ")
                        .IsUnique()
                        .HasFilter("cnpj IS NOT NULL");

                    b.HasIndex("CPF")
                        .IsUnique()
                        .HasFilter("cpf IS NOT NULL");

                    b.HasIndex("Nome")
                        .HasDatabaseName("ix_fornecedor_nome");

                    b.ToTable("fornecedores", (string)null);

                    b.HasDiscriminator().HasValue("Fornecedor");
                });

            modelBuilder.Entity("AutoGestao.Entidades.Parcela", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("AlteradoPorUsuarioId")
                        .HasColumnType("integer")
                        .HasColumnName("alterado_por_usuario_id");

                    b.Property<int?>("CriadoPorUsuarioId")
                        .HasColumnType("integer")
                        .HasColumnName("criado_por_usuario_id");

                    b.Property<DateTime>("DataAlteracao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasDefaultValue(new DateTime(2025, 9, 26, 6, 52, 52, 76, DateTimeKind.Utc).AddTicks(5229))
                        .HasColumnName("data_alteracao");

                    b.Property<DateTime>("DataCadastro")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("data_cadastro");

                    b.Property<DateTime?>("DataPagamento")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("data_pagamento");

                    b.Property<DateTime>("DataVencimento")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("data_vencimento");

                    b.Property<int>("NumeroParcela")
                        .HasColumnType("integer")
                        .HasColumnName("numero_parcela");

                    b.Property<string>("Observacoes")
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)")
                        .HasColumnName("observacoes");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<decimal>("Valor")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("valor");

                    b.Property<decimal?>("ValorPago")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("valor_pago");

                    b.Property<int>("VendaId")
                        .HasColumnType("integer")
                        .HasColumnName("venda_id");

                    b.HasKey("Id")
                        .HasName("pk_parcelas");

                    b.HasIndex("DataVencimento");

                    b.HasIndex("Status");

                    b.HasIndex("VendaId");

                    b.HasIndex("DataVencimento", "Status")
                        .HasDatabaseName("ix_parcela_vencimento_status");

                    b.ToTable("parcelas", (string)null);

                    b.HasDiscriminator().HasValue("Parcela");
                });

            modelBuilder.Entity("AutoGestao.Entidades.Tarefa", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("AlteradoPorUsuarioId")
                        .HasColumnType("integer")
                        .HasColumnName("alterado_por_usuario_id");

                    b.Property<int?>("CriadoPorUsuarioId")
                        .HasColumnType("integer")
                        .HasColumnName("criado_por_usuario_id");

                    b.Property<DateTime>("DataAlteracao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasDefaultValue(new DateTime(2025, 9, 26, 6, 52, 52, 78, DateTimeKind.Utc).AddTicks(1239))
                        .HasColumnName("data_alteracao");

                    b.Property<DateTime>("DataCadastro")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("data_cadastro");

                    b.Property<DateTime?>("DataConclusao")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("data_conclusao");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("data_criacao");

                    b.Property<DateTime?>("DataVencimento")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("data_vencimento");

                    b.Property<string>("Descricao")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("descricao");

                    b.Property<int>("Prioridade")
                        .HasColumnType("integer")
                        .HasColumnName("prioridade");

                    b.Property<int?>("ResponsavelId")
                        .HasColumnType("integer")
                        .HasColumnName("responsavel_id");

                    b.Property<int?>("ResponsavelUsuarioId")
                        .HasColumnType("integer")
                        .HasColumnName("responsavel_usuario_id");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("titulo");

                    b.HasKey("Id")
                        .HasName("pk_tarefas");

                    b.HasIndex("DataVencimento");

                    b.HasIndex("ResponsavelId");

                    b.HasIndex("ResponsavelUsuarioId");

                    b.HasIndex("Status");

                    b.ToTable("tarefas", (string)null);

                    b.HasDiscriminator().HasValue("Tarefa");
                });

            modelBuilder.Entity("AutoGestao.Entidades.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("AlteradoPorUsuarioId")
                        .HasColumnType("integer")
                        .HasColumnName("alterado_por_usuario_id");

                    b.Property<bool>("Ativo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("ativo");

                    b.Property<string>("CPF")
                        .HasMaxLength(14)
                        .HasColumnType("character varying(14)")
                        .HasColumnName("cpf");

                    b.Property<int?>("CriadoPorUsuarioId")
                        .HasColumnType("integer")
                        .HasColumnName("criado_por_usuario_id");

                    b.Property<DateTime>("DataAlteracao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasDefaultValue(new DateTime(2025, 9, 26, 6, 52, 52, 79, DateTimeKind.Utc).AddTicks(4450))
                        .HasColumnName("data_alteracao");

                    b.Property<DateTime>("DataCadastro")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("data_cadastro");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("email");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)")
                        .HasColumnName("nome");

                    b.Property<string>("Observacoes")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("observacoes");

                    b.Property<int>("Perfil")
                        .HasColumnType("integer")
                        .HasColumnName("perfil");

                    b.Property<string>("SenhaHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("senha_hash");

                    b.Property<string>("Telefone")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("telefone");

                    b.Property<DateTime?>("UltimoLogin")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("ultimo_login");

                    b.HasKey("Id")
                        .HasName("pk_usuarios");

                    b.HasIndex("CPF")
                        .IsUnique();

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("usuarios", (string)null);

                    b.HasDiscriminator().HasValue("Usuario");
                });

            modelBuilder.Entity("AutoGestao.Entidades.Veiculos.Veiculo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("AlteradoPorUsuarioId")
                        .HasColumnType("integer")
                        .HasColumnName("alterado_por_usuario_id");

                    b.Property<int?>("AnoFabricacao")
                        .HasColumnType("integer")
                        .HasColumnName("ano_fabricacao");

                    b.Property<int?>("AnoModelo")
                        .HasColumnType("integer")
                        .HasColumnName("ano_modelo");

                    b.Property<int>("Cambio")
                        .HasColumnType("integer")
                        .HasColumnName("cambio");

                    b.Property<string>("Chassi")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("chassi");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("codigo");

                    b.Property<int>("Combustivel")
                        .HasColumnType("integer")
                        .HasColumnName("combustivel");

                    b.Property<int?>("CriadoPorUsuarioId")
                        .HasColumnType("integer")
                        .HasColumnName("criado_por_usuario_id");

                    b.Property<DateTime>("DataAlteracao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasDefaultValue(new DateTime(2025, 9, 26, 6, 52, 52, 74, DateTimeKind.Utc).AddTicks(129))
                        .HasColumnName("data_alteracao");

                    b.Property<DateTime>("DataCadastro")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("data_cadastro");

                    b.Property<DateTime?>("DataSaida")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("data_saida");

                    b.Property<int>("Especie")
                        .HasColumnType("integer")
                        .HasColumnName("especie");

                    b.Property<long?>("KmSaida")
                        .HasColumnType("bigint")
                        .HasColumnName("km_saida");

                    b.Property<string>("Motorizacao")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("motorizacao");

                    b.Property<string>("Observacoes")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("observacoes");

                    b.Property<string>("Opcionais")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("opcionais");

                    b.Property<int>("OrigemVeiculo")
                        .HasColumnType("integer")
                        .HasColumnName("origem_veiculo");

                    b.Property<int>("PericiaCautelar")
                        .HasColumnType("integer")
                        .HasColumnName("pericia_cautelar");

                    b.Property<string>("Placa")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("placa");

                    b.Property<int>("Portas")
                        .HasColumnType("integer")
                        .HasColumnName("portas");

                    b.Property<decimal?>("PrecoCompra")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("preco_compra");

                    b.Property<decimal?>("PrecoVenda")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("preco_venda");

                    b.Property<int?>("ProprietarioId")
                        .HasColumnType("integer")
                        .HasColumnName("proprietario_id");

                    b.Property<int?>("Quilometragem")
                        .HasColumnType("integer")
                        .HasColumnName("quilometragem");

                    b.Property<string>("Renavam")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("renavam");

                    b.Property<int>("Situacao")
                        .HasColumnType("integer")
                        .HasColumnName("situacao");

                    b.Property<int>("StatusVeiculo")
                        .HasColumnType("integer")
                        .HasColumnName("status_veiculo");

                    b.Property<int>("TipoVeiculo")
                        .HasColumnType("integer")
                        .HasColumnName("tipo_veiculo");

                    b.Property<int?>("VeiculoCorId")
                        .HasColumnType("integer")
                        .HasColumnName("veiculo_cor_id");

                    b.Property<int?>("VeiculoFilialId")
                        .HasColumnType("integer")
                        .HasColumnName("veiculo_filial_id");

                    b.Property<int?>("VeiculoLocalizacaoId")
                        .HasColumnType("integer")
                        .HasColumnName("veiculo_localizacao_id");

                    b.Property<int>("VeiculoMarcaId")
                        .HasColumnType("integer")
                        .HasColumnName("veiculo_marca_id");

                    b.Property<int>("VeiculoMarcaModeloId")
                        .HasColumnType("integer")
                        .HasColumnName("veiculo_marca_modelo_id");

                    b.HasKey("Id")
                        .HasName("pk_veiculos");

                    b.HasIndex("Chassi")
                        .IsUnique()
                        .HasFilter("chassi IS NOT NULL");

                    b.HasIndex("Codigo")
                        .IsUnique();

                    b.HasIndex("Placa")
                        .IsUnique();

                    b.HasIndex("ProprietarioId");

                    b.HasIndex("Renavam")
                        .IsUnique()
                        .HasFilter("renavam IS NOT NULL");

                    b.HasIndex("Situacao");

                    b.HasIndex("StatusVeiculo");

                    b.HasIndex("VeiculoCorId");

                    b.HasIndex("VeiculoFilialId");

                    b.HasIndex("VeiculoLocalizacaoId");

                    b.HasIndex("VeiculoMarcaId");

                    b.HasIndex("VeiculoMarcaModeloId");

                    b.HasIndex("Situacao", "VeiculoMarcaId")
                        .HasDatabaseName("ix_veiculo_situacao_marca");

                    b.ToTable("veiculos", (string)null);

                    b.HasDiscriminator().HasValue("Veiculo");
                });

            modelBuilder.Entity("AutoGestao.Entidades.Veiculos.VeiculoCor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("AlteradoPorUsuarioId")
                        .HasColumnType("integer")
                        .HasColumnName("alterado_por_usuario_id");

                    b.Property<int?>("CriadoPorUsuarioId")
                        .HasColumnType("integer")
                        .HasColumnName("criado_por_usuario_id");

                    b.Property<DateTime>("DataAlteracao")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("data_alteracao");

                    b.Property<DateTime>("DataCadastro")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("data_cadastro");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("descricao");

                    b.HasKey("Id")
                        .HasName("pk_veiculo_cores");

                    b.HasIndex("Descricao")
                        .IsUnique();

                    b.ToTable("veiculo_cores", (string)null);

                    b.HasDiscriminator().HasValue("VeiculoCor");
                });

            modelBuilder.Entity("AutoGestao.Entidades.Veiculos.VeiculoDocumento", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("AlteradoPorUsuarioId")
                        .HasColumnType("integer")
                        .HasColumnName("alterado_por_usuario_id");

                    b.Property<string>("CaminhoArquivo")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("caminho_arquivo");

                    b.Property<int?>("CriadoPorUsuarioId")
                        .HasColumnType("integer")
                        .HasColumnName("criado_por_usuario_id");

                    b.Property<DateTime>("DataAlteracao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasDefaultValue(new DateTime(2025, 9, 26, 6, 52, 52, 75, DateTimeKind.Utc).AddTicks(7905))
                        .HasColumnName("data_alteracao");

                    b.Property<DateTime>("DataCadastro")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("data_cadastro");

                    b.Property<DateTime>("DataUpload")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("data_upload");

                    b.Property<string>("NomeArquivo")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("nome_arquivo");

                    b.Property<string>("Observacoes")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("observacoes");

                    b.Property<int>("TipoDocumento")
                        .HasColumnType("integer")
                        .HasColumnName("tipo_documento");

                    b.Property<int>("VeiculoId")
                        .HasColumnType("integer")
                        .HasColumnName("veiculo_id");

                    b.HasKey("Id")
                        .HasName("pk_veiculo_documentos");

                    b.HasIndex("VeiculoId");

                    b.ToTable("veiculo_documentos", (string)null);

                    b.HasDiscriminator().HasValue("VeiculoDocumento");
                });

            modelBuilder.Entity("AutoGestao.Entidades.Veiculos.VeiculoFilial", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("AlteradoPorUsuarioId")
                        .HasColumnType("integer")
                        .HasColumnName("alterado_por_usuario_id");

                    b.Property<int?>("CriadoPorUsuarioId")
                        .HasColumnType("integer")
                        .HasColumnName("criado_por_usuario_id");

                    b.Property<DateTime>("DataAlteracao")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("data_alteracao");

                    b.Property<DateTime>("DataCadastro")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("data_cadastro");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("descricao");

                    b.HasKey("Id")
                        .HasName("pk_veiculo_filiais");

                    b.HasIndex("Descricao")
                        .IsUnique();

                    b.ToTable("veiculo_filiais", (string)null);

                    b.HasDiscriminator().HasValue("VeiculoFilial");
                });

            modelBuilder.Entity("AutoGestao.Entidades.Veiculos.VeiculoFoto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("AlteradoPorUsuarioId")
                        .HasColumnType("integer")
                        .HasColumnName("alterado_por_usuario_id");

                    b.Property<string>("CaminhoArquivo")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("caminho_arquivo");

                    b.Property<int?>("CriadoPorUsuarioId")
                        .HasColumnType("integer")
                        .HasColumnName("criado_por_usuario_id");

                    b.Property<DateTime>("DataAlteracao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasDefaultValue(new DateTime(2025, 9, 26, 6, 52, 52, 75, DateTimeKind.Utc).AddTicks(5721))
                        .HasColumnName("data_alteracao");

                    b.Property<DateTime>("DataCadastro")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("data_cadastro");

                    b.Property<DateTime>("DataUpload")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("data_upload");

                    b.Property<string>("Descricao")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("descricao");

                    b.Property<string>("NomeArquivo")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("nome_arquivo");

                    b.Property<bool>("Principal")
                        .HasColumnType("boolean")
                        .HasColumnName("principal");

                    b.Property<int>("VeiculoId")
                        .HasColumnType("integer")
                        .HasColumnName("veiculo_id");

                    b.HasKey("Id")
                        .HasName("pk_veiculo_fotos");

                    b.HasIndex("VeiculoId");

                    b.ToTable("veiculo_fotos", (string)null);

                    b.HasDiscriminator().HasValue("VeiculoFoto");
                });

            modelBuilder.Entity("AutoGestao.Entidades.Veiculos.VeiculoLocalizacao", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("AlteradoPorUsuarioId")
                        .HasColumnType("integer")
                        .HasColumnName("alterado_por_usuario_id");

                    b.Property<int?>("CriadoPorUsuarioId")
                        .HasColumnType("integer")
                        .HasColumnName("criado_por_usuario_id");

                    b.Property<DateTime>("DataAlteracao")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("data_alteracao");

                    b.Property<DateTime>("DataCadastro")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("data_cadastro");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("descricao");

                    b.HasKey("Id")
                        .HasName("pk_veiculo_localizacoes");

                    b.HasIndex("Descricao")
                        .IsUnique();

                    b.ToTable("veiculo_localizacoes", (string)null);

                    b.HasDiscriminator().HasValue("VeiculoLocalizacao");
                });

            modelBuilder.Entity("AutoGestao.Entidades.Veiculos.VeiculoMarca", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("AlteradoPorUsuarioId")
                        .HasColumnType("integer")
                        .HasColumnName("alterado_por_usuario_id");

                    b.Property<int?>("CriadoPorUsuarioId")
                        .HasColumnType("integer")
                        .HasColumnName("criado_por_usuario_id");

                    b.Property<DateTime>("DataAlteracao")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("data_alteracao");

                    b.Property<DateTime>("DataCadastro")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("data_cadastro");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("descricao");

                    b.HasKey("Id")
                        .HasName("pk_veiculo_marcas");

                    b.HasIndex("Descricao")
                        .IsUnique();

                    b.ToTable("veiculo_marcas", (string)null);

                    b.HasDiscriminator().HasValue("VeiculoMarca");
                });

            modelBuilder.Entity("AutoGestao.Entidades.Veiculos.VeiculoMarcaModelo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("AlteradoPorUsuarioId")
                        .HasColumnType("integer")
                        .HasColumnName("alterado_por_usuario_id");

                    b.Property<int?>("CriadoPorUsuarioId")
                        .HasColumnType("integer")
                        .HasColumnName("criado_por_usuario_id");

                    b.Property<DateTime>("DataAlteracao")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("data_alteracao");

                    b.Property<DateTime>("DataCadastro")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("data_cadastro");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("descricao");

                    b.Property<int?>("VeiculoMarcaId")
                        .HasColumnType("integer")
                        .HasColumnName("veiculo_marca_id");

                    b.HasKey("Id")
                        .HasName("pk_veiculo_marca_modelos");

                    b.HasIndex("VeiculoMarcaId");

                    b.ToTable("veiculo_marca_modelos", (string)null);

                    b.HasDiscriminator().HasValue("VeiculoMarcaModelo");
                });

            modelBuilder.Entity("AutoGestao.Entidades.Venda", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("AlteradoPorUsuarioId")
                        .HasColumnType("integer")
                        .HasColumnName("alterado_por_usuario_id");

                    b.Property<int>("ClienteId")
                        .HasColumnType("integer")
                        .HasColumnName("cliente_id");

                    b.Property<int?>("CriadoPorUsuarioId")
                        .HasColumnType("integer")
                        .HasColumnName("criado_por_usuario_id");

                    b.Property<DateTime>("DataAlteracao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasDefaultValue(new DateTime(2025, 9, 26, 6, 52, 52, 76, DateTimeKind.Utc).AddTicks(294))
                        .HasColumnName("data_alteracao");

                    b.Property<DateTime>("DataCadastro")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("data_cadastro");

                    b.Property<DateTime>("DataVenda")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("data_venda");

                    b.Property<int?>("FormaPagamento")
                        .HasColumnType("integer")
                        .HasColumnName("forma_pagamento");

                    b.Property<int?>("NumeroParcelas")
                        .HasColumnType("integer")
                        .HasColumnName("numero_parcelas");

                    b.Property<string>("Observacoes")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("observacoes");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<decimal?>("ValorEntrada")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("valor_entrada");

                    b.Property<decimal>("ValorVenda")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("valor_venda");

                    b.Property<int>("VeiculoId")
                        .HasColumnType("integer")
                        .HasColumnName("veiculo_id");

                    b.Property<int>("VendedorId")
                        .HasColumnType("integer")
                        .HasColumnName("vendedor_id");

                    b.HasKey("Id")
                        .HasName("pk_vendas");

                    b.HasIndex("ClienteId");

                    b.HasIndex("DataVenda");

                    b.HasIndex("Status");

                    b.HasIndex("VeiculoId");

                    b.HasIndex("VendedorId");

                    b.HasIndex("DataVenda", "Status")
                        .HasDatabaseName("ix_venda_data_status");

                    b.ToTable("vendas", (string)null);

                    b.HasDiscriminator().HasValue("Venda");
                });

            modelBuilder.Entity("AutoGestao.Entidades.Vendedor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("AlteradoPorUsuarioId")
                        .HasColumnType("integer")
                        .HasColumnName("alterado_por_usuario_id");

                    b.Property<bool>("Ativo")
                        .HasColumnType("boolean")
                        .HasColumnName("ativo");

                    b.Property<string>("CPF")
                        .IsRequired()
                        .HasMaxLength(14)
                        .HasColumnType("character varying(14)")
                        .HasColumnName("cpf");

                    b.Property<string>("Celular")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("celular");

                    b.Property<int?>("CriadoPorUsuarioId")
                        .HasColumnType("integer")
                        .HasColumnName("criado_por_usuario_id");

                    b.Property<DateTime>("DataAlteracao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasDefaultValue(new DateTime(2025, 9, 26, 6, 52, 52, 73, DateTimeKind.Utc).AddTicks(2532))
                        .HasColumnName("data_alteracao");

                    b.Property<DateTime>("DataCadastro")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("data_cadastro");

                    b.Property<string>("Email")
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("email");

                    b.Property<decimal?>("Meta")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("meta");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)")
                        .HasColumnName("nome");

                    b.Property<decimal?>("PercentualComissao")
                        .HasColumnType("decimal(5,2)")
                        .HasColumnName("percentual_comissao");

                    b.Property<string>("Telefone")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("telefone");

                    b.HasKey("Id")
                        .HasName("pk_vendedores");

                    b.HasIndex("CPF")
                        .IsUnique();

                    b.HasIndex("Nome")
                        .HasDatabaseName("ix_vendedor_nome");

                    b.ToTable("vendedores", (string)null);

                    b.HasDiscriminator().HasValue("Vendedor");
                });

            modelBuilder.Entity("AutoGestao.Entidades.AuditLog", b =>
                {
                    b.HasOne("AutoGestao.Entidades.Usuario", "Usuario")
                        .WithMany("AuditLogs")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("AutoGestao.Entidades.Avaliacao", b =>
                {
                    b.HasOne("AutoGestao.Entidades.Cliente", "Cliente")
                        .WithMany("Avaliacoes")
                        .HasForeignKey("ClienteId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("AutoGestao.Entidades.Veiculos.VeiculoMarca", "VeiculoMarca")
                        .WithMany()
                        .HasForeignKey("VeiculoMarcaId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("AutoGestao.Entidades.Veiculos.VeiculoMarcaModelo", "VeiculoMarcaModelo")
                        .WithMany()
                        .HasForeignKey("VeiculoMarcaModeloId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("AutoGestao.Entidades.Vendedor", "VendedorResponsavel")
                        .WithMany("Avaliacoes")
                        .HasForeignKey("VendedorResponsavelId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Cliente");

                    b.Navigation("VeiculoMarca");

                    b.Navigation("VeiculoMarcaModelo");

                    b.Navigation("VendedorResponsavel");
                });

            modelBuilder.Entity("AutoGestao.Entidades.Cliente", b =>
                {
                    b.HasOne("AutoGestao.Entidades.Usuario", null)
                        .WithMany()
                        .HasForeignKey("AlteradoPorUsuarioId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("AutoGestao.Entidades.Usuario", null)
                        .WithMany()
                        .HasForeignKey("CriadoPorUsuarioId")
                        .OnDelete(DeleteBehavior.SetNull);
                });

            modelBuilder.Entity("AutoGestao.Entidades.Despesa", b =>
                {
                    b.HasOne("AutoGestao.Entidades.DespesaTipo", "DespesaTipo")
                        .WithMany()
                        .HasForeignKey("DespesaTipoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AutoGestao.Entidades.Fornecedor", "Fornecedor")
                        .WithMany()
                        .HasForeignKey("FornecedorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AutoGestao.Entidades.Veiculos.Veiculo", "Veiculo")
                        .WithMany("Despesas")
                        .HasForeignKey("VeiculoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("DespesaTipo");

                    b.Navigation("Fornecedor");

                    b.Navigation("Veiculo");
                });

            modelBuilder.Entity("AutoGestao.Entidades.Parcela", b =>
                {
                    b.HasOne("AutoGestao.Entidades.Venda", "Venda")
                        .WithMany("Parcelas")
                        .HasForeignKey("VendaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Venda");
                });

            modelBuilder.Entity("AutoGestao.Entidades.Tarefa", b =>
                {
                    b.HasOne("AutoGestao.Entidades.Vendedor", "Responsavel")
                        .WithMany("Tarefas")
                        .HasForeignKey("ResponsavelId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("AutoGestao.Entidades.Usuario", "ResponsavelUsuario")
                        .WithMany("TarefasResponsavel")
                        .HasForeignKey("ResponsavelUsuarioId");

                    b.Navigation("Responsavel");

                    b.Navigation("ResponsavelUsuario");
                });

            modelBuilder.Entity("AutoGestao.Entidades.Veiculos.Veiculo", b =>
                {
                    b.HasOne("AutoGestao.Entidades.Cliente", "Proprietario")
                        .WithMany("Veiculos")
                        .HasForeignKey("ProprietarioId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("AutoGestao.Entidades.Veiculos.VeiculoCor", "VeiculoCor")
                        .WithMany()
                        .HasForeignKey("VeiculoCorId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("AutoGestao.Entidades.Veiculos.VeiculoFilial", "VeiculoFilial")
                        .WithMany()
                        .HasForeignKey("VeiculoFilialId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("AutoGestao.Entidades.Veiculos.VeiculoLocalizacao", "VeiculoLocalizacao")
                        .WithMany()
                        .HasForeignKey("VeiculoLocalizacaoId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("AutoGestao.Entidades.Veiculos.VeiculoMarca", "VeiculoMarca")
                        .WithMany()
                        .HasForeignKey("VeiculoMarcaId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .IsRequired();

                    b.HasOne("AutoGestao.Entidades.Veiculos.VeiculoMarcaModelo", "VeiculoMarcaModelo")
                        .WithMany()
                        .HasForeignKey("VeiculoMarcaModeloId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .IsRequired();

                    b.Navigation("Proprietario");

                    b.Navigation("VeiculoCor");

                    b.Navigation("VeiculoFilial");

                    b.Navigation("VeiculoLocalizacao");

                    b.Navigation("VeiculoMarca");

                    b.Navigation("VeiculoMarcaModelo");
                });

            modelBuilder.Entity("AutoGestao.Entidades.Veiculos.VeiculoDocumento", b =>
                {
                    b.HasOne("AutoGestao.Entidades.Veiculos.Veiculo", "Veiculo")
                        .WithMany("Documentos")
                        .HasForeignKey("VeiculoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Veiculo");
                });

            modelBuilder.Entity("AutoGestao.Entidades.Veiculos.VeiculoFoto", b =>
                {
                    b.HasOne("AutoGestao.Entidades.Veiculos.Veiculo", "Veiculo")
                        .WithMany("Fotos")
                        .HasForeignKey("VeiculoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Veiculo");
                });

            modelBuilder.Entity("AutoGestao.Entidades.Veiculos.VeiculoMarcaModelo", b =>
                {
                    b.HasOne("AutoGestao.Entidades.Veiculos.VeiculoMarca", "VeiculoMarca")
                        .WithMany()
                        .HasForeignKey("VeiculoMarcaId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("VeiculoMarca");
                });

            modelBuilder.Entity("AutoGestao.Entidades.Venda", b =>
                {
                    b.HasOne("AutoGestao.Entidades.Cliente", "Cliente")
                        .WithMany("Vendas")
                        .HasForeignKey("ClienteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AutoGestao.Entidades.Veiculos.Veiculo", "Veiculo")
                        .WithMany("Vendas")
                        .HasForeignKey("VeiculoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AutoGestao.Entidades.Vendedor", "Vendedor")
                        .WithMany("Vendas")
                        .HasForeignKey("VendedorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Cliente");

                    b.Navigation("Veiculo");

                    b.Navigation("Vendedor");
                });

            modelBuilder.Entity("AutoGestao.Entidades.Cliente", b =>
                {
                    b.Navigation("Avaliacoes");

                    b.Navigation("Veiculos");

                    b.Navigation("Vendas");
                });

            modelBuilder.Entity("AutoGestao.Entidades.Usuario", b =>
                {
                    b.Navigation("AuditLogs");

                    b.Navigation("TarefasResponsavel");
                });

            modelBuilder.Entity("AutoGestao.Entidades.Veiculos.Veiculo", b =>
                {
                    b.Navigation("Despesas");

                    b.Navigation("Documentos");

                    b.Navigation("Fotos");

                    b.Navigation("Vendas");
                });

            modelBuilder.Entity("AutoGestao.Entidades.Venda", b =>
                {
                    b.Navigation("Parcelas");
                });

            modelBuilder.Entity("AutoGestao.Entidades.Vendedor", b =>
                {
                    b.Navigation("Avaliacoes");

                    b.Navigation("Tarefas");

                    b.Navigation("Vendas");
                });
#pragma warning restore 612, 618
        }
    }
}
