CREATE TABLE IF NOT EXISTS "__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL,
    CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId")
);

START TRANSACTION;
CREATE TABLE empresas (
    id bigint GENERATED BY DEFAULT AS IDENTITY,
    razao_social character varying(250) NOT NULL,
    cnpj character varying(18),
    telefone character varying(20),
    celular character varying(20),
    email character varying(150),
    cep character varying(10),
    estado integer NOT NULL,
    cidade character varying(100),
    endereco character varying(500),
    numero character varying(20),
    bairro character varying(100),
    complemento character varying(150),
    observacoes character varying(2000),
    id_empresa bigint NOT NULL,
    ativo boolean NOT NULL,
    data_cadastro timestamp without time zone NOT NULL,
    data_alteracao timestamp without time zone NOT NULL,
    criado_por_usuario_id bigint,
    alterado_por_usuario_id bigint,
    empresa_id bigint,
    CONSTRAINT pk_empresas PRIMARY KEY (id),
    CONSTRAINT "FK_empresas_empresas_empresa_id" FOREIGN KEY (empresa_id) REFERENCES empresas (id)
);

CREATE TABLE aliquotas_impostos (
    id bigint GENERATED BY DEFAULT AS IDENTITY,
    tipo_imposto integer NOT NULL,
    aliquota_percentual numeric(5,2) NOT NULL,
    regime_tributario integer,
    estado integer,
    cidade character varying(100),
    data_vigencia_inicial timestamp without time zone NOT NULL,
    data_vigencia_final timestamp without time zone,
    observacoes character varying(500),
    id_empresa bigint NOT NULL,
    ativo boolean NOT NULL,
    data_cadastro timestamp without time zone NOT NULL,
    data_alteracao timestamp without time zone NOT NULL,
    criado_por_usuario_id bigint,
    alterado_por_usuario_id bigint,
    empresa_id bigint,
    CONSTRAINT pk_aliquotas_impostos PRIMARY KEY (id),
    CONSTRAINT "FK_aliquotas_impostos_empresas_empresa_id" FOREIGN KEY (empresa_id) REFERENCES empresas (id)
);

CREATE TABLE clientes (
    id bigint GENERATED BY DEFAULT AS IDENTITY,
    cep character varying(10),
    estado integer NOT NULL,
    cidade character varying(100),
    endereco character varying(500),
    numero character varying(20),
    bairro character varying(100),
    complemento character varying(150),
    observacoes character varying(2000),
    foto_cliente character varying(10000),
    documento_rg character varying(10000),
    id_empresa bigint NOT NULL,
    ativo boolean NOT NULL,
    data_cadastro timestamp without time zone NOT NULL,
    data_alteracao timestamp without time zone NOT NULL,
    criado_por_usuario_id bigint,
    alterado_por_usuario_id bigint,
    empresa_id bigint,
    tipo_pessoa integer NOT NULL,
    nome character varying(250) NOT NULL,
    data_nascimento timestamp without time zone,
    cpf character varying(14),
    rg character varying(20),
    cnpj character varying(18),
    email character varying(150),
    telefone character varying(20),
    celular character varying(20),
    CONSTRAINT pk_clientes PRIMARY KEY (id),
    CONSTRAINT "FK_clientes_empresas_empresa_id" FOREIGN KEY (empresa_id) REFERENCES empresas (id)
);

CREATE TABLE cnaes (
    id bigint GENERATED BY DEFAULT AS IDENTITY,
    codigo character varying(10) NOT NULL,
    descricao character varying(500) NOT NULL,
    aliquota_iss numeric,
    id_empresa bigint NOT NULL,
    ativo boolean NOT NULL,
    data_cadastro timestamp without time zone NOT NULL,
    data_alteracao timestamp without time zone NOT NULL,
    criado_por_usuario_id bigint,
    alterado_por_usuario_id bigint,
    empresa_id bigint,
    CONSTRAINT pk_cnaes PRIMARY KEY (id),
    CONSTRAINT "FK_cnaes_empresas_empresa_id" FOREIGN KEY (empresa_id) REFERENCES empresas (id)
);

CREATE TABLE contadores_responsaveis (
    id bigint GENERATED BY DEFAULT AS IDENTITY,
    nome character varying(200) NOT NULL,
    cpf character varying(14) NOT NULL,
    crc character varying(20) NOT NULL,
    estado_crc integer NOT NULL,
    email character varying(100) NOT NULL,
    telefone character varying(20),
    celular character varying(20),
    escritorio character varying(200),
    cnpjescritorio character varying(18),
    observacoes character varying(500),
    id_empresa bigint NOT NULL,
    ativo boolean NOT NULL,
    data_cadastro timestamp without time zone NOT NULL,
    data_alteracao timestamp without time zone NOT NULL,
    criado_por_usuario_id bigint,
    alterado_por_usuario_id bigint,
    empresa_id bigint,
    CONSTRAINT pk_contadores_responsaveis PRIMARY KEY (id),
    CONSTRAINT "FK_contadores_responsaveis_empresas_empresa_id" FOREIGN KEY (empresa_id) REFERENCES empresas (id)
);

CREATE TABLE plano_contas (
    id bigint GENERATED BY DEFAULT AS IDENTITY,
    codigo character varying(20) NOT NULL,
    descricao character varying(200) NOT NULL,
    tipo_conta integer NOT NULL,
    natureza integer NOT NULL,
    conta_pai_id bigint,
    nivel integer NOT NULL,
    conta_analitica boolean NOT NULL,
    aceita_lancamento boolean NOT NULL,
    exibir_na_dre boolean NOT NULL,
    exibir_no_balancete boolean NOT NULL,
    observacoes character varying(500),
    id_empresa bigint NOT NULL,
    ativo boolean NOT NULL,
    data_cadastro timestamp without time zone NOT NULL,
    data_alteracao timestamp without time zone NOT NULL,
    criado_por_usuario_id bigint,
    alterado_por_usuario_id bigint,
    empresa_id bigint,
    CONSTRAINT pk_plano_contas PRIMARY KEY (id),
    CONSTRAINT "FK_plano_contas_empresas_empresa_id" FOREIGN KEY (empresa_id) REFERENCES empresas (id),
    CONSTRAINT "FK_plano_contas_plano_contas_conta_pai_id" FOREIGN KEY (conta_pai_id) REFERENCES plano_contas (id) ON DELETE RESTRICT
);

CREATE TABLE report_templates (
    id bigint GENERATED BY DEFAULT AS IDENTITY,
    nome character varying(200) NOT NULL,
    descricao character varying(500),
    tipo_entidade character varying(100) NOT NULL,
    template_json text NOT NULL,
    padrao boolean NOT NULL DEFAULT FALSE,
    ativo boolean NOT NULL DEFAULT TRUE,
    id_empresa bigint NOT NULL,
    data_cadastro timestamp without time zone NOT NULL,
    data_alteracao timestamp without time zone NOT NULL,
    criado_por_usuario_id bigint,
    alterado_por_usuario_id bigint,
    empresa_id bigint,
    CONSTRAINT pk_report_templates PRIMARY KEY (id),
    CONSTRAINT "FK_report_templates_empresas_empresa_id" FOREIGN KEY (empresa_id) REFERENCES empresas (id)
);

CREATE TABLE usuarios (
    id bigint GENERATED BY DEFAULT AS IDENTITY,
    nome character varying(250) NOT NULL,
    email character varying(150) NOT NULL,
    cpf character varying(14),
    telefone character varying(20),
    perfil integer NOT NULL,
    ultimo_login timestamp without time zone,
    senha_hash character varying(255) NOT NULL,
    observacoes character varying(2000),
    id_empresa bigint NOT NULL,
    ativo boolean NOT NULL DEFAULT TRUE,
    data_cadastro timestamp without time zone NOT NULL,
    data_alteracao timestamp without time zone NOT NULL,
    criado_por_usuario_id bigint,
    alterado_por_usuario_id bigint,
    CONSTRAINT pk_usuarios PRIMARY KEY (id),
    CONSTRAINT "FK_usuarios_empresas_id_empresa" FOREIGN KEY (id_empresa) REFERENCES empresas (id) ON DELETE SET NULL
);

CREATE TABLE empresas_clientes (
    id bigint GENERATED BY DEFAULT AS IDENTITY,
    razao_social character varying(200) NOT NULL,
    nome_fantasia character varying(200),
    cnpj character varying(18) NOT NULL,
    inscricao_estadual character varying(20),
    inscricao_municipal character varying(20),
    regime_tributario integer NOT NULL,
    cnaeprincipal_id bigint,
    contador_responsavel_id bigint,
    email character varying(100),
    telefone character varying(20),
    cep character varying(9),
    estado integer NOT NULL,
    cidade character varying(100),
    endereco character varying(200),
    numero character varying(10),
    complemento character varying(100),
    observacoes character varying(1000),
    id_empresa bigint NOT NULL,
    ativo boolean NOT NULL,
    data_cadastro timestamp without time zone NOT NULL,
    data_alteracao timestamp without time zone NOT NULL,
    criado_por_usuario_id bigint,
    alterado_por_usuario_id bigint,
    empresa_id bigint,
    CONSTRAINT pk_empresas_clientes PRIMARY KEY (id),
    CONSTRAINT "FK_empresas_clientes_cnaes_cnaeprincipal_id" FOREIGN KEY (cnaeprincipal_id) REFERENCES cnaes (id) ON DELETE SET NULL,
    CONSTRAINT "FK_empresas_clientes_contadores_responsaveis_contador_responsa~" FOREIGN KEY (contador_responsavel_id) REFERENCES contadores_responsaveis (id) ON DELETE SET NULL,
    CONSTRAINT "FK_empresas_clientes_empresas_empresa_id" FOREIGN KEY (empresa_id) REFERENCES empresas (id)
);

CREATE TABLE audit_logs (
    id bigint GENERATED BY DEFAULT AS IDENTITY,
    id_empresa bigint NOT NULL,
    usuario_id bigint,
    entidade_nome character varying(100) NOT NULL,
    entidade_id character varying(50) NOT NULL,
    tipo_operacao integer NOT NULL,
    tabela_nome character varying(100),
    valores_antigos text,
    valores_novos text,
    campos_alterados text,
    ip_cliente character varying(45),
    url_requisicao character varying(500),
    metodo_http character varying(10),
    sucesso boolean NOT NULL,
    mensagem_erro character varying(2000),
    duracao_ms bigint,
    data_hora timestamp without time zone NOT NULL,
    CONSTRAINT pk_audit_logs PRIMARY KEY (id),
    CONSTRAINT "FK_audit_logs_empresas_id_empresa" FOREIGN KEY (id_empresa) REFERENCES empresas (id) ON DELETE SET NULL,
    CONSTRAINT "FK_audit_logs_usuarios_usuario_id" FOREIGN KEY (usuario_id) REFERENCES usuarios (id) ON DELETE SET NULL
);

CREATE TABLE certificados_digitais (
    id bigint GENERATED BY DEFAULT AS IDENTITY,
    empresa_cliente_id bigint NOT NULL,
    titular character varying(200) NOT NULL,
    data_validade timestamp without time zone NOT NULL,
    senha character varying(50),
    arquivo_certificado character varying(500),
    id_empresa bigint NOT NULL,
    ativo boolean NOT NULL,
    data_cadastro timestamp without time zone NOT NULL,
    data_alteracao timestamp without time zone NOT NULL,
    criado_por_usuario_id bigint,
    alterado_por_usuario_id bigint,
    empresa_id bigint,
    CONSTRAINT pk_certificados_digitais PRIMARY KEY (id),
    CONSTRAINT "FK_certificados_digitais_empresas_clientes_empresa_cliente_id" FOREIGN KEY (empresa_cliente_id) REFERENCES empresas_clientes (id) ON DELETE CASCADE,
    CONSTRAINT "FK_certificados_digitais_empresas_empresa_id" FOREIGN KEY (empresa_id) REFERENCES empresas (id)
);

CREATE TABLE dados_bancarios (
    id bigint GENERATED BY DEFAULT AS IDENTITY,
    empresa_cliente_id bigint NOT NULL,
    nome_banco character varying(100) NOT NULL,
    codigo_banco character varying(3) NOT NULL,
    agencia character varying(10) NOT NULL,
    digito_agencia character varying(2),
    numero_conta character varying(20) NOT NULL,
    digito_conta character varying(2) NOT NULL,
    tipo_conta integer NOT NULL,
    chave_pix character varying(100),
    conta_principal boolean NOT NULL,
    observacoes character varying(500),
    id_empresa bigint NOT NULL,
    ativo boolean NOT NULL,
    data_cadastro timestamp without time zone NOT NULL,
    data_alteracao timestamp without time zone NOT NULL,
    criado_por_usuario_id bigint,
    alterado_por_usuario_id bigint,
    empresa_id bigint,
    CONSTRAINT pk_dados_bancarios PRIMARY KEY (id),
    CONSTRAINT "FK_dados_bancarios_empresas_clientes_empresa_cliente_id" FOREIGN KEY (empresa_cliente_id) REFERENCES empresas_clientes (id) ON DELETE CASCADE,
    CONSTRAINT "FK_dados_bancarios_empresas_empresa_id" FOREIGN KEY (empresa_id) REFERENCES empresas (id)
);

CREATE TABLE notas_fiscais (
    id bigint GENERATED BY DEFAULT AS IDENTITY,
    numero integer NOT NULL,
    serie integer NOT NULL,
    chave_acesso character varying(44),
    modelo integer NOT NULL,
    tipo integer NOT NULL,
    status integer NOT NULL,
    empresa_cliente_id bigint NOT NULL,
    data_emissao timestamp without time zone,
    data_saida_entrada timestamp without time zone,
    valor_total numeric(18,2) NOT NULL,
    valor_produtos numeric(18,2) NOT NULL,
    valor_servicos numeric(18,2) NOT NULL,
    valor_icms numeric(18,2) NOT NULL,
    valor_ipi numeric(18,2) NOT NULL,
    valor_pis numeric(18,2) NOT NULL,
    valor_cofins numeric(18,2) NOT NULL,
    arquivo_xml character varying(500),
    arquivo_pdf character varying(500),
    observacoes character varying(1000),
    id_empresa bigint NOT NULL,
    ativo boolean NOT NULL,
    data_cadastro timestamp without time zone NOT NULL,
    data_alteracao timestamp without time zone NOT NULL,
    criado_por_usuario_id bigint,
    alterado_por_usuario_id bigint,
    empresa_id bigint,
    CONSTRAINT pk_notas_fiscais PRIMARY KEY (id),
    CONSTRAINT "FK_notas_fiscais_empresas_clientes_empresa_cliente_id" FOREIGN KEY (empresa_cliente_id) REFERENCES empresas_clientes (id) ON DELETE CASCADE,
    CONSTRAINT "FK_notas_fiscais_empresas_empresa_id" FOREIGN KEY (empresa_id) REFERENCES empresas (id)
);

CREATE TABLE obrigacoes_fiscais (
    id bigint GENERATED BY DEFAULT AS IDENTITY,
    empresa_cliente_id bigint NOT NULL,
    tipo_obrigacao integer NOT NULL,
    periodicidade integer NOT NULL,
    competencia timestamp without time zone NOT NULL,
    data_vencimento timestamp without time zone NOT NULL,
    status integer NOT NULL,
    data_entrega timestamp without time zone,
    numero_recibo character varying(100),
    arquivo_enviado character varying(500),
    arquivo_recibo character varying(500),
    observacoes character varying(1000),
    id_empresa bigint NOT NULL,
    ativo boolean NOT NULL,
    data_cadastro timestamp without time zone NOT NULL,
    data_alteracao timestamp without time zone NOT NULL,
    criado_por_usuario_id bigint,
    alterado_por_usuario_id bigint,
    empresa_id bigint,
    CONSTRAINT pk_obrigacoes_fiscais PRIMARY KEY (id),
    CONSTRAINT "FK_obrigacoes_fiscais_empresas_clientes_empresa_cliente_id" FOREIGN KEY (empresa_cliente_id) REFERENCES empresas_clientes (id) ON DELETE CASCADE,
    CONSTRAINT "FK_obrigacoes_fiscais_empresas_empresa_id" FOREIGN KEY (empresa_id) REFERENCES empresas (id)
);

CREATE TABLE parametros_fiscais (
    id bigint GENERATED BY DEFAULT AS IDENTITY,
    empresa_cliente_id bigint NOT NULL,
    ambiente_nfe integer NOT NULL,
    serie_nfe integer NOT NULL,
    proximo_numero_nfe integer NOT NULL,
    serie_nfse integer NOT NULL,
    proximo_numero_nfse integer NOT NULL,
    cfop_padrao_venda character varying(6),
    cfop_padrao_compra character varying(6),
    cfop_padrao_servico character varying(6),
    cst_icms_padrao character varying(3),
    cst_pis_padrao character varying(2),
    cst_cofins_padrao character varying(2),
    mensagem_padrao_nfe character varying(500),
    mensagem_padrao_nfse character varying(500),
    enviar_email_automatico boolean NOT NULL,
    email_padrao_copia character varying(100),
    id_empresa bigint NOT NULL,
    ativo boolean NOT NULL,
    data_cadastro timestamp without time zone NOT NULL,
    data_alteracao timestamp without time zone NOT NULL,
    criado_por_usuario_id bigint,
    alterado_por_usuario_id bigint,
    empresa_id bigint,
    CONSTRAINT pk_parametros_fiscais PRIMARY KEY (id),
    CONSTRAINT "FK_parametros_fiscais_empresas_clientes_empresa_cliente_id" FOREIGN KEY (empresa_cliente_id) REFERENCES empresas_clientes (id) ON DELETE CASCADE,
    CONSTRAINT "FK_parametros_fiscais_empresas_empresa_id" FOREIGN KEY (empresa_id) REFERENCES empresas (id)
);

CREATE TABLE lancamentos_contabeis (
    id bigint GENERATED BY DEFAULT AS IDENTITY,
    data_lancamento timestamp without time zone NOT NULL,
    tipo_lancamento integer NOT NULL,
    empresa_cliente_id bigint NOT NULL,
    conta_debito_id bigint NOT NULL,
    conta_credito_id bigint NOT NULL,
    valor numeric(18,2) NOT NULL,
    historico character varying(500) NOT NULL,
    complemento character varying(1000),
    numero_documento character varying(50),
    nota_fiscal_id bigint,
    conciliado boolean NOT NULL,
    data_conciliacao timestamp without time zone,
    "PlanoContasId" bigint,
    id_empresa bigint NOT NULL,
    ativo boolean NOT NULL,
    data_cadastro timestamp without time zone NOT NULL,
    data_alteracao timestamp without time zone NOT NULL,
    criado_por_usuario_id bigint,
    alterado_por_usuario_id bigint,
    empresa_id bigint,
    CONSTRAINT pk_lancamentos_contabeis PRIMARY KEY (id),
    CONSTRAINT "FK_lancamentos_contabeis_empresas_clientes_empresa_cliente_id" FOREIGN KEY (empresa_cliente_id) REFERENCES empresas_clientes (id) ON DELETE RESTRICT,
    CONSTRAINT "FK_lancamentos_contabeis_empresas_empresa_id" FOREIGN KEY (empresa_id) REFERENCES empresas (id),
    CONSTRAINT "FK_lancamentos_contabeis_notas_fiscais_nota_fiscal_id" FOREIGN KEY (nota_fiscal_id) REFERENCES notas_fiscais (id),
    CONSTRAINT "FK_lancamentos_contabeis_plano_contas_PlanoContasId" FOREIGN KEY ("PlanoContasId") REFERENCES plano_contas (id),
    CONSTRAINT "FK_lancamentos_contabeis_plano_contas_conta_credito_id" FOREIGN KEY (conta_credito_id) REFERENCES plano_contas (id) ON DELETE RESTRICT,
    CONSTRAINT "FK_lancamentos_contabeis_plano_contas_conta_debito_id" FOREIGN KEY (conta_debito_id) REFERENCES plano_contas (id) ON DELETE RESTRICT
);

CREATE TABLE notas_fiscais_itens (
    id bigint GENERATED BY DEFAULT AS IDENTITY,
    nota_fiscal_id bigint NOT NULL,
    descricao character varying(200) NOT NULL,
    codigo character varying(50),
    ncm character varying(8),
    cfop character varying(4),
    quantidade numeric(18,4) NOT NULL,
    valor_unitario numeric(18,2) NOT NULL,
    valor_total numeric(18,2) NOT NULL,
    id_empresa bigint NOT NULL,
    ativo boolean NOT NULL,
    data_cadastro timestamp without time zone NOT NULL,
    data_alteracao timestamp without time zone NOT NULL,
    criado_por_usuario_id bigint,
    alterado_por_usuario_id bigint,
    empresa_id bigint,
    CONSTRAINT pk_notas_fiscais_itens PRIMARY KEY (id),
    CONSTRAINT "FK_notas_fiscais_itens_empresas_empresa_id" FOREIGN KEY (empresa_id) REFERENCES empresas (id),
    CONSTRAINT "FK_notas_fiscais_itens_notas_fiscais_nota_fiscal_id" FOREIGN KEY (nota_fiscal_id) REFERENCES notas_fiscais (id) ON DELETE CASCADE
);

CREATE INDEX "IX_aliquotas_impostos_empresa_id" ON aliquotas_impostos (empresa_id);

CREATE INDEX "IX_audit_logs_data_hora" ON audit_logs (data_hora);

CREATE INDEX "IX_audit_logs_entidade_nome_entidade_id" ON audit_logs (entidade_nome, entidade_id);

CREATE INDEX "IX_audit_logs_id_empresa" ON audit_logs (id_empresa);

CREATE INDEX "IX_audit_logs_usuario_id" ON audit_logs (usuario_id);

CREATE INDEX "IX_certificados_digitais_empresa_cliente_id" ON certificados_digitais (empresa_cliente_id);

CREATE INDEX "IX_certificados_digitais_empresa_id" ON certificados_digitais (empresa_id);

CREATE INDEX ix_cliente_nome ON clientes (nome);

CREATE UNIQUE INDEX "IX_clientes_cnpj" ON clientes (cnpj) WHERE cnpj IS NOT NULL;

CREATE UNIQUE INDEX "IX_clientes_cpf" ON clientes (cpf) WHERE cpf IS NOT NULL;

CREATE INDEX "IX_clientes_empresa_id" ON clientes (empresa_id);

CREATE INDEX "IX_cnaes_empresa_id" ON cnaes (empresa_id);

CREATE INDEX "IX_contadores_responsaveis_empresa_id" ON contadores_responsaveis (empresa_id);

CREATE INDEX "IX_dados_bancarios_empresa_cliente_id" ON dados_bancarios (empresa_cliente_id);

CREATE INDEX "IX_dados_bancarios_empresa_id" ON dados_bancarios (empresa_id);

CREATE INDEX "IX_empresas_empresa_id" ON empresas (empresa_id);

CREATE INDEX "IX_empresas_clientes_cnaeprincipal_id" ON empresas_clientes (cnaeprincipal_id);

CREATE INDEX "IX_empresas_clientes_contador_responsavel_id" ON empresas_clientes (contador_responsavel_id);

CREATE INDEX "IX_empresas_clientes_empresa_id" ON empresas_clientes (empresa_id);

CREATE INDEX "IX_lancamentos_contabeis_conta_credito_id" ON lancamentos_contabeis (conta_credito_id);

CREATE INDEX "IX_lancamentos_contabeis_conta_debito_id" ON lancamentos_contabeis (conta_debito_id);

CREATE INDEX "IX_lancamentos_contabeis_empresa_cliente_id" ON lancamentos_contabeis (empresa_cliente_id);

CREATE INDEX "IX_lancamentos_contabeis_empresa_id" ON lancamentos_contabeis (empresa_id);

CREATE INDEX "IX_lancamentos_contabeis_nota_fiscal_id" ON lancamentos_contabeis (nota_fiscal_id);

CREATE INDEX "IX_lancamentos_contabeis_PlanoContasId" ON lancamentos_contabeis ("PlanoContasId");

CREATE INDEX "IX_notas_fiscais_empresa_cliente_id" ON notas_fiscais (empresa_cliente_id);

CREATE INDEX "IX_notas_fiscais_empresa_id" ON notas_fiscais (empresa_id);

CREATE INDEX "IX_notas_fiscais_itens_empresa_id" ON notas_fiscais_itens (empresa_id);

CREATE INDEX "IX_notas_fiscais_itens_nota_fiscal_id" ON notas_fiscais_itens (nota_fiscal_id);

CREATE INDEX "IX_obrigacoes_fiscais_empresa_cliente_id" ON obrigacoes_fiscais (empresa_cliente_id);

CREATE INDEX "IX_obrigacoes_fiscais_empresa_id" ON obrigacoes_fiscais (empresa_id);

CREATE INDEX "IX_parametros_fiscais_empresa_cliente_id" ON parametros_fiscais (empresa_cliente_id);

CREATE INDEX "IX_parametros_fiscais_empresa_id" ON parametros_fiscais (empresa_id);

CREATE INDEX "IX_plano_contas_conta_pai_id" ON plano_contas (conta_pai_id);

CREATE INDEX "IX_plano_contas_empresa_id" ON plano_contas (empresa_id);

CREATE INDEX "IX_report_templates_empresa_id" ON report_templates (empresa_id);

CREATE INDEX "IX_report_templates_tipo_entidade" ON report_templates (tipo_entidade);

CREATE INDEX "IX_report_templates_tipo_entidade_padrao" ON report_templates (tipo_entidade, padrao);

CREATE INDEX "IX_usuarios_id_empresa" ON usuarios (id_empresa);

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20251107115646_InitialCreate', '9.0.9');

ALTER TABLE usuarios ADD id_empresa_cliente bigint;

CREATE UNIQUE INDEX "IX_usuarios_id_empresa_cliente" ON usuarios (id_empresa_cliente);

ALTER TABLE usuarios ADD CONSTRAINT "FK_usuarios_empresas_clientes_id_empresa_cliente" FOREIGN KEY (id_empresa_cliente) REFERENCES empresas_clientes (id);

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20251108050547_Vinculo', '9.0.9');

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20251108053305_AdicionarIdEmpresaClienteEmUsuario', '9.0.9');

CREATE TABLE usuario_empresa_cliente (
    id bigint GENERATED BY DEFAULT AS IDENTITY,
    id_usuario bigint NOT NULL,
    id_empresa_cliente bigint NOT NULL,
    data_vinculo timestamp without time zone NOT NULL,
    ativo boolean NOT NULL,
    CONSTRAINT pk_usuario_empresa_cliente PRIMARY KEY (id),
    CONSTRAINT "FK_usuario_empresa_cliente_empresas_clientes_id_empresa_cliente" FOREIGN KEY (id_empresa_cliente) REFERENCES empresas_clientes (id) ON DELETE CASCADE,
    CONSTRAINT "FK_usuario_empresa_cliente_usuarios_id_usuario" FOREIGN KEY (id_usuario) REFERENCES usuarios (id) ON DELETE CASCADE
);

CREATE INDEX "IX_usuario_empresa_cliente_id_empresa_cliente" ON usuario_empresa_cliente (id_empresa_cliente);

CREATE INDEX "IX_usuario_empresa_cliente_id_usuario" ON usuario_empresa_cliente (id_usuario);

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20251108061107_AdicionarUsuarioEmpresaCliente', '9.0.9');

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20251108062044_AdicionarUsuarioEmpresaCliente2', '9.0.9');

ALTER TABLE usuario_empresa_cliente ADD id_empresa bigint NOT NULL DEFAULT 0;

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20251108065702_AdicionarFluxoUsuarioCliente', '9.0.9');

COMMIT;

