-- =============================================
-- Script de Insert: CNAEs
-- Descrição: 50 CNAEs mais comuns no Brasil
-- =============================================

INSERT INTO cnaes (id, codigo, descricao, id_empresa, ativo, data_cadastro, data_alteracao) VALUES
(1, '4711-3/01', 'Comércio varejista de mercadorias em geral, com predominância de produtos alimentícios - minimercados, mercearias e armazéns', 1, true, NOW(), NOW()),
(2, '4711-3/02', 'Comércio varejista de mercadorias em geral, com predominância de produtos alimentícios - supermercados', 1, true, NOW(), NOW()),
(3, '4712-1/00', 'Comércio varejista de mercadorias em geral, com predominância de produtos alimentícios - hipermercados', 1, true, NOW(), NOW()),
(4, '4721-1/01', 'Padaria e confeitaria com predominância de produção própria', 1, true, NOW(), NOW()),
(5, '4721-1/02', 'Padaria e confeitaria com predominância de revenda', 1, true, NOW(), NOW()),
(6, '4729-6/99', 'Comércio varejista de produtos alimentícios em geral ou especializado em produtos alimentícios não especificados anteriormente', 1, true, NOW(), NOW()),
(7, '4751-2/01', 'Comércio varejista especializado de equipamentos e suprimentos de informática', 1, true, NOW(), NOW()),
(8, '4752-1/00', 'Comércio varejista especializado de equipamentos de telefonia e comunicação', 1, true, NOW(), NOW()),
(9, '4753-9/00', 'Comércio varejista especializado de eletrodomésticos e equipamentos de áudio e vídeo', 1, true, NOW(), NOW()),
(10, '4754-7/01', 'Comércio varejista de móveis', 1, true, NOW(), NOW()),
(11, '4755-5/01', 'Comércio varejista de tecidos', 1, true, NOW(), NOW()),
(12, '4781-4/00', 'Comércio varejista de artigos do vestuário e acessórios', 1, true, NOW(), NOW()),
(13, '4782-2/01', 'Comércio varejista de calçados', 1, true, NOW(), NOW()),
(14, '4783-1/01', 'Comércio varejista de artigos farmacêuticos, sem manipulação de fórmulas', 1, true, NOW(), NOW()),
(15, '4783-1/02', 'Comércio varejista de artigos farmacêuticos, com manipulação de fórmulas', 1, true, NOW(), NOW()),
(16, '4789-0/01', 'Comércio varejista de suvenires, bijuterias e artesanatos', 1, true, NOW(), NOW()),
(17, '5611-2/01', 'Restaurantes e similares', 1, true, NOW(), NOW()),
(18, '5611-2/03', 'Lanchonetes, casas de chá, de sucos e similares', 1, true, NOW(), NOW()),
(19, '5620-1/01', 'Fornecimento de alimentos preparados preponderantemente para empresas', 1, true, NOW(), NOW()),
(20, '5620-1/02', 'Serviços de alimentação para eventos e recepções - bufê', 1, true, NOW(), NOW()),
(21, '6201-5/00', 'Desenvolvimento de programas de computador sob encomenda', 1, true, NOW(), NOW()),
(22, '6202-3/00', 'Desenvolvimento e licenciamento de programas de computador customizáveis', 1, true, NOW(), NOW()),
(23, '6203-1/00', 'Desenvolvimento e licenciamento de programas de computador não customizáveis', 1, true, NOW(), NOW()),
(24, '6204-0/00', 'Consultoria em tecnologia da informação', 1, true, NOW(), NOW()),
(25, '6209-1/00', 'Suporte técnico, manutenção e outros serviços em tecnologia da informação', 1, true, NOW(), NOW()),
(26, '6311-9/00', 'Tratamento de dados, provedores de serviços de aplicação e serviços de hospedagem na internet', 1, true, NOW(), NOW()),
(27, '6319-4/00', 'Portais, provedores de conteúdo e outros serviços de informação na internet', 1, true, NOW(), NOW()),
(28, '6421-2/00', 'Bancos comerciais', 1, true, NOW(), NOW()),
(29, '6422-1/00', 'Bancos múltiplos, com carteira comercial', 1, true, NOW(), NOW()),
(30, '6423-9/00', 'Caixas econômicas', 1, true, NOW(), NOW()),
(31, '6911-7/01', 'Serviços advocatícios', 1, true, NOW(), NOW()),
(32, '6920-6/01', 'Atividades de contabilidade', 1, true, NOW(), NOW()),
(33, '6920-6/02', 'Atividades de consultoria e auditoria contábil e tributária', 1, true, NOW(), NOW()),
(34, '7020-4/00', 'Atividades de consultoria em gestão empresarial, exceto consultoria técnica específica', 1, true, NOW(), NOW()),
(35, '7111-1/00', 'Serviços de arquitetura', 1, true, NOW(), NOW()),
(36, '7112-0/00', 'Serviços de engenharia', 1, true, NOW(), NOW()),
(37, '7119-7/01', 'Serviços de cartografia, topografia e geodésia', 1, true, NOW(), NOW()),
(38, '7210-0/00', 'Pesquisa e desenvolvimento experimental em ciências físicas e naturais', 1, true, NOW(), NOW()),
(39, '7311-4/00', 'Agências de publicidade', 1, true, NOW(), NOW()),
(40, '7312-2/00', 'Agenciamento de espaços para publicidade, exceto em veículos de comunicação', 1, true, NOW(), NOW()),
(41, '7319-0/02', 'Promoção de vendas', 1, true, NOW(), NOW()),
(42, '7490-1/04', 'Atividades de intermediação e agenciamento de serviços e negócios em geral, exceto imobiliários', 1, true, NOW(), NOW()),
(43, '8011-1/01', 'Atividades de vigilância e segurança privada', 1, true, NOW(), NOW()),
(44, '8020-0/01', 'Atividades de monitoramento de sistemas de segurança eletrônico', 1, true, NOW(), NOW()),
(45, '8511-2/00', 'Educação infantil - creche', 1, true, NOW(), NOW()),
(46, '8512-1/00', 'Educação infantil - pré-escola', 1, true, NOW(), NOW()),
(47, '8513-9/00', 'Ensino fundamental', 1, true, NOW(), NOW()),
(48, '8520-1/00', 'Ensino médio', 1, true, NOW(), NOW()),
(49, '8531-7/00', 'Educação superior - graduação', 1, true, NOW(), NOW()),
(50, '8532-5/00', 'Educação superior - graduação e pós-graduação', 1, true, NOW(), NOW());

-- Atualizar a sequência
SELECT setval('cnaes_id_seq', 50, true);
